#pragma once

#define MIKAN_CLIENT_API_VERSION		0

#define MIKAN_SERVER_API_VERSION_KEY		"ServerVersion"
#define MIKAN_SERVER_API_VERSION_VALUE		0

#define MIKAN_MIN_ALLOWED_CLIENT_API_VERSION_KEY		"MinAllowedVersion"
#define MIKAN_MIN_ALLOWED_CLIENT_API_VERSION_VALUE		0