// This file is auto generated. DO NOT EDIT.

import { TypeRegistry } from '../Serialization/JsonDeserializer.js';
import { MikanEvent, MikanRequest, MikanResponse } from './MikanAPITypes.js';
import { MikanAnchorComponentValues, MikanAnchorSystemValues } from './MikanAnchorTypes.js';
import { MikanCameraNewFrameEvent } from './MikanCameraEvents.js';
import { AllocateCameraRenderTargetTextures, FreeCameraRenderTargetTextures, PublishCameraRenderTargetTextures, WriteCameraColorRenderTargetTexture, WriteCameraDepthRenderTargetTexture } from './MikanCameraRequests.js';
import { MikanCameraComponentValues } from './MikanCameraTypes.js';
import { MikanConnectedEvent, MikanDisconnectedEvent } from './MikanClientEvents.js';
import { DisposeClientRequest, InitClientRequest } from './MikanClientRequests.js';
import { MikanClientInfo } from './MikanClientTypes.js';
import { MikanComponentValues } from './MikanComponentTypes.js';
import { MikanCompositorComponentValues } from './MikanCompositorTypes.js';
import { MikanClientAPIVersion, MikanRenderTargetDescriptor } from './MikanCoreTypes.js';
import { MikanEditorSystemValues } from './MikanEditorTypes.js';
import { FunctionDescriptorResponse, GetFunctionListRequest, InvokeComponentFunctionRequest, InvokeSystemFunctionRequest } from './MikanFunctionRequests.js';
import { MikanFunctionDescriptor } from './MikanFunctionTypes.js';
import { ArucoMarkerImageResponse, GetArucoMarkerImageRequest } from './MikanMarkerRequests.js';
import { MikanMarkerComponentValues, MikanMarkerSystemValues } from './MikanMarkerTypes.js';
import { MikanMatrix3d, MikanMatrix4d, MikanMatrix4f, MikanMatrix4x3d, MikanQuatd, MikanQuatf, MikanRotator3f, MikanTransform, MikanVector2d, MikanVector2f, MikanVector2i, MikanVector3d, MikanVector3f, MikanVector4d, MikanVector4f } from './MikanMathTypes.js';
import { MikanPropertyUpdateEvent } from './MikanPropertyEvents.js';
import { ComponentGetValuesRequest, ComponentGetValuesResponse, ComponentListResponse, GetComponentListRequest, GetPropertyDescriptors, PropertyDescriptorResponse, PropertyGetValueRequest, PropertyGetValueResponse, PropertySetValueRequest, PropertySetValueResponse, SetPropertyNotifyMode, SystemCreateObjectRequest, SystemDestroyObjectRequest, SystemGetValuesRequest, SystemGetValuesResponse } from './MikanPropertyRequests.js';
import { MikanPropertyDescriptor, MikanPropertyValue, MikanSystemValues } from './MikanPropertyTypes.js';
import { MikanAppStageChangedEvent, MikanRemoteControlEvent } from './MikanRemoteControlEvents.js';
import { GetAppStageInfo, MikanAppStageInfoResponse, MikanRemoteControlCommand, MikanRemoteControlCommandResult, PopAppStage, PushAppStage } from './MikanRemoteControlRequest.js';
import { MikanAppStageInfo } from './MikanRemoteControlTypes.js';
import { MikanSceneComponentValues, MikanSceneSystemValues } from './MikanSceneTypes.js';
import { MikanScriptMessagePostedEvent } from './MikanScriptEvents.js';
import { InvokeComponentScriptTrigger, SendScriptMessage } from './MikanScriptRequest.js';
import { MikanScriptMessageInfo } from './MikanScriptTypes.js';
import { MikanStageComponentValues } from './MikanStageTypes.js';
import { GetModelStencilRenderGeometry, MikanStencilModelRenderGeometryResponse } from './MikanStencilRequest.js';
import { MikanBoxStencilComponentValues, MikanBoxStencilSystemValues, MikanModelStencilComponentValues, MikanModelStencilSystemValues, MikanQuadStencilComponentValues, MikanQuadStencilSystemValues, MikanStencilComponentValues, MikanStencilModelRenderGeometry, MikanTriagulatedMesh } from './MikanStencilTypes.js';
import { MikanTextureSourceClosedEvent, MikanTextureSourceOpenedEvent } from './MikanTextureSourceEvents.js';
import { MikanClientTextureSourceValues, MikanSpoutTextureSourceValues, MikanTextureSourceValues } from './MikanTextureSourceTypes.js';
import { MikanTrackingMountComponentValues } from './MikanTrackingMountTypes.js';
import { MikanMarkerTrackingVolumeComponentValues, MikanTrackingVolumeComponentValues, MikanVRTrackingVolumeComponentValues } from './MikanTrackingVolumeTypes.js';
import { MikanTransformComponentValues } from './MikanTransformTypes.js';
import { MikanVRDeviceComponentValues } from './MikanVRDeviceTypes.js';
import { MikanBoolArrayValue, MikanBoolValue, MikanDoubleValue, MikanFloatArrayValue, MikanFloatValue, MikanIntArrayValue, MikanIntValue, MikanLongValue, MikanMatrix4fValue, MikanQuatdValue, MikanQuatfValue, MikanStringArrayValue, MikanStringMapValue, MikanStringValue, MikanVariant, MikanVariantBase, MikanVector2dValue, MikanVector2fValue, MikanVector3dValue, MikanVector3fValue, MikanVector4dValue, MikanVector4fValue } from './MikanVariantTypes.js';
import { MikanVideoSourceClosedEvent, MikanVideoSourceModeChangedEvent, MikanVideoSourceOpenedEvent } from './MikanVideoSourceEvents.js';
import { GetVideoSourceIntrinsics, GetVideoSourceMode, MikanVideoSourceIntrinsicsResponse, MikanVideoSourceModeResponse, SetUSBVideoSourceDevice, SetUSBVideoSourceFormat, SetUSBVideoSourceFrameRate, SetUSBVideoSourceResolution } from './MikanVideoSourceRequest.js';
import { MikanBaseIntrinsics, MikanDistortionCoefficients, MikanMonoIntrinsics, MikanNetworkVideoSourceValues, MikanStereoIntrinsics, MikanUSBVideoSourceSystemValues, MikanUSBVideoSourceValues, MikanVideoSourceIntrinsics, MikanVideoSourceValues } from './MikanVideoSourceTypes.js';

export function registerAllTypes(): void {
  TypeRegistry.register('MikanEvent', MikanEvent);
  TypeRegistry.register('MikanRequest', MikanRequest);
  TypeRegistry.register('MikanResponse', MikanResponse);
  TypeRegistry.register('MikanAnchorComponentValues', MikanAnchorComponentValues);
  TypeRegistry.register('MikanAnchorSystemValues', MikanAnchorSystemValues);
  TypeRegistry.register('MikanCameraNewFrameEvent', MikanCameraNewFrameEvent);
  TypeRegistry.register('AllocateCameraRenderTargetTextures', AllocateCameraRenderTargetTextures);
  TypeRegistry.register('FreeCameraRenderTargetTextures', FreeCameraRenderTargetTextures);
  TypeRegistry.register('PublishCameraRenderTargetTextures', PublishCameraRenderTargetTextures);
  TypeRegistry.register('WriteCameraColorRenderTargetTexture', WriteCameraColorRenderTargetTexture);
  TypeRegistry.register('WriteCameraDepthRenderTargetTexture', WriteCameraDepthRenderTargetTexture);
  TypeRegistry.register('MikanCameraComponentValues', MikanCameraComponentValues);
  TypeRegistry.register('MikanConnectedEvent', MikanConnectedEvent);
  TypeRegistry.register('MikanDisconnectedEvent', MikanDisconnectedEvent);
  TypeRegistry.register('DisposeClientRequest', DisposeClientRequest);
  TypeRegistry.register('InitClientRequest', InitClientRequest);
  TypeRegistry.register('MikanClientInfo', MikanClientInfo);
  TypeRegistry.register('MikanComponentValues', MikanComponentValues);
  TypeRegistry.register('MikanCompositorComponentValues', MikanCompositorComponentValues);
  TypeRegistry.register('MikanClientAPIVersion', MikanClientAPIVersion);
  TypeRegistry.register('MikanRenderTargetDescriptor', MikanRenderTargetDescriptor);
  TypeRegistry.register('MikanEditorSystemValues', MikanEditorSystemValues);
  TypeRegistry.register('FunctionDescriptorResponse', FunctionDescriptorResponse);
  TypeRegistry.register('GetFunctionListRequest', GetFunctionListRequest);
  TypeRegistry.register('InvokeComponentFunctionRequest', InvokeComponentFunctionRequest);
  TypeRegistry.register('InvokeSystemFunctionRequest', InvokeSystemFunctionRequest);
  TypeRegistry.register('MikanFunctionDescriptor', MikanFunctionDescriptor);
  TypeRegistry.register('ArucoMarkerImageResponse', ArucoMarkerImageResponse);
  TypeRegistry.register('GetArucoMarkerImageRequest', GetArucoMarkerImageRequest);
  TypeRegistry.register('MikanMarkerComponentValues', MikanMarkerComponentValues);
  TypeRegistry.register('MikanMarkerSystemValues', MikanMarkerSystemValues);
  TypeRegistry.register('MikanMatrix3d', MikanMatrix3d);
  TypeRegistry.register('MikanMatrix4d', MikanMatrix4d);
  TypeRegistry.register('MikanMatrix4f', MikanMatrix4f);
  TypeRegistry.register('MikanMatrix4x3d', MikanMatrix4x3d);
  TypeRegistry.register('MikanQuatd', MikanQuatd);
  TypeRegistry.register('MikanQuatf', MikanQuatf);
  TypeRegistry.register('MikanRotator3f', MikanRotator3f);
  TypeRegistry.register('MikanTransform', MikanTransform);
  TypeRegistry.register('MikanVector2d', MikanVector2d);
  TypeRegistry.register('MikanVector2f', MikanVector2f);
  TypeRegistry.register('MikanVector2i', MikanVector2i);
  TypeRegistry.register('MikanVector3d', MikanVector3d);
  TypeRegistry.register('MikanVector3f', MikanVector3f);
  TypeRegistry.register('MikanVector4d', MikanVector4d);
  TypeRegistry.register('MikanVector4f', MikanVector4f);
  TypeRegistry.register('MikanPropertyUpdateEvent', MikanPropertyUpdateEvent);
  TypeRegistry.register('ComponentGetValuesRequest', ComponentGetValuesRequest);
  TypeRegistry.register('ComponentGetValuesResponse', ComponentGetValuesResponse);
  TypeRegistry.register('ComponentListResponse', ComponentListResponse);
  TypeRegistry.register('GetComponentListRequest', GetComponentListRequest);
  TypeRegistry.register('GetPropertyDescriptors', GetPropertyDescriptors);
  TypeRegistry.register('PropertyDescriptorResponse', PropertyDescriptorResponse);
  TypeRegistry.register('PropertyGetValueRequest', PropertyGetValueRequest);
  TypeRegistry.register('PropertyGetValueResponse', PropertyGetValueResponse);
  TypeRegistry.register('PropertySetValueRequest', PropertySetValueRequest);
  TypeRegistry.register('PropertySetValueResponse', PropertySetValueResponse);
  TypeRegistry.register('SetPropertyNotifyMode', SetPropertyNotifyMode);
  TypeRegistry.register('SystemCreateObjectRequest', SystemCreateObjectRequest);
  TypeRegistry.register('SystemDestroyObjectRequest', SystemDestroyObjectRequest);
  TypeRegistry.register('SystemGetValuesRequest', SystemGetValuesRequest);
  TypeRegistry.register('SystemGetValuesResponse', SystemGetValuesResponse);
  TypeRegistry.register('MikanPropertyDescriptor', MikanPropertyDescriptor);
  TypeRegistry.register('MikanPropertyValue', MikanPropertyValue);
  TypeRegistry.register('MikanSystemValues', MikanSystemValues);
  TypeRegistry.register('MikanAppStageChangedEvent', MikanAppStageChangedEvent);
  TypeRegistry.register('MikanRemoteControlEvent', MikanRemoteControlEvent);
  TypeRegistry.register('GetAppStageInfo', GetAppStageInfo);
  TypeRegistry.register('MikanAppStageInfoResponse', MikanAppStageInfoResponse);
  TypeRegistry.register('MikanRemoteControlCommand', MikanRemoteControlCommand);
  TypeRegistry.register('MikanRemoteControlCommandResult', MikanRemoteControlCommandResult);
  TypeRegistry.register('PopAppStage', PopAppStage);
  TypeRegistry.register('PushAppStage', PushAppStage);
  TypeRegistry.register('MikanAppStageInfo', MikanAppStageInfo);
  TypeRegistry.register('MikanSceneComponentValues', MikanSceneComponentValues);
  TypeRegistry.register('MikanSceneSystemValues', MikanSceneSystemValues);
  TypeRegistry.register('MikanScriptMessagePostedEvent', MikanScriptMessagePostedEvent);
  TypeRegistry.register('InvokeComponentScriptTrigger', InvokeComponentScriptTrigger);
  TypeRegistry.register('SendScriptMessage', SendScriptMessage);
  TypeRegistry.register('MikanScriptMessageInfo', MikanScriptMessageInfo);
  TypeRegistry.register('MikanStageComponentValues', MikanStageComponentValues);
  TypeRegistry.register('GetModelStencilRenderGeometry', GetModelStencilRenderGeometry);
  TypeRegistry.register('MikanStencilModelRenderGeometryResponse', MikanStencilModelRenderGeometryResponse);
  TypeRegistry.register('MikanBoxStencilComponentValues', MikanBoxStencilComponentValues);
  TypeRegistry.register('MikanBoxStencilSystemValues', MikanBoxStencilSystemValues);
  TypeRegistry.register('MikanModelStencilComponentValues', MikanModelStencilComponentValues);
  TypeRegistry.register('MikanModelStencilSystemValues', MikanModelStencilSystemValues);
  TypeRegistry.register('MikanQuadStencilComponentValues', MikanQuadStencilComponentValues);
  TypeRegistry.register('MikanQuadStencilSystemValues', MikanQuadStencilSystemValues);
  TypeRegistry.register('MikanStencilComponentValues', MikanStencilComponentValues);
  TypeRegistry.register('MikanStencilModelRenderGeometry', MikanStencilModelRenderGeometry);
  TypeRegistry.register('MikanTriagulatedMesh', MikanTriagulatedMesh);
  TypeRegistry.register('MikanTextureSourceClosedEvent', MikanTextureSourceClosedEvent);
  TypeRegistry.register('MikanTextureSourceOpenedEvent', MikanTextureSourceOpenedEvent);
  TypeRegistry.register('MikanClientTextureSourceValues', MikanClientTextureSourceValues);
  TypeRegistry.register('MikanSpoutTextureSourceValues', MikanSpoutTextureSourceValues);
  TypeRegistry.register('MikanTextureSourceValues', MikanTextureSourceValues);
  TypeRegistry.register('MikanTrackingMountComponentValues', MikanTrackingMountComponentValues);
  TypeRegistry.register('MikanMarkerTrackingVolumeComponentValues', MikanMarkerTrackingVolumeComponentValues);
  TypeRegistry.register('MikanTrackingVolumeComponentValues', MikanTrackingVolumeComponentValues);
  TypeRegistry.register('MikanVRTrackingVolumeComponentValues', MikanVRTrackingVolumeComponentValues);
  TypeRegistry.register('MikanTransformComponentValues', MikanTransformComponentValues);
  TypeRegistry.register('MikanVRDeviceComponentValues', MikanVRDeviceComponentValues);
  TypeRegistry.register('MikanBoolArrayValue', MikanBoolArrayValue);
  TypeRegistry.register('MikanBoolValue', MikanBoolValue);
  TypeRegistry.register('MikanDoubleValue', MikanDoubleValue);
  TypeRegistry.register('MikanFloatArrayValue', MikanFloatArrayValue);
  TypeRegistry.register('MikanFloatValue', MikanFloatValue);
  TypeRegistry.register('MikanIntArrayValue', MikanIntArrayValue);
  TypeRegistry.register('MikanIntValue', MikanIntValue);
  TypeRegistry.register('MikanLongValue', MikanLongValue);
  TypeRegistry.register('MikanMatrix4fValue', MikanMatrix4fValue);
  TypeRegistry.register('MikanQuatdValue', MikanQuatdValue);
  TypeRegistry.register('MikanQuatfValue', MikanQuatfValue);
  TypeRegistry.register('MikanStringArrayValue', MikanStringArrayValue);
  TypeRegistry.register('MikanStringMapValue', MikanStringMapValue);
  TypeRegistry.register('MikanStringValue', MikanStringValue);
  TypeRegistry.register('MikanVariant', MikanVariant);
  TypeRegistry.register('MikanVariantBase', MikanVariantBase);
  TypeRegistry.register('MikanVector2dValue', MikanVector2dValue);
  TypeRegistry.register('MikanVector2fValue', MikanVector2fValue);
  TypeRegistry.register('MikanVector3dValue', MikanVector3dValue);
  TypeRegistry.register('MikanVector3fValue', MikanVector3fValue);
  TypeRegistry.register('MikanVector4dValue', MikanVector4dValue);
  TypeRegistry.register('MikanVector4fValue', MikanVector4fValue);
  TypeRegistry.register('MikanVideoSourceClosedEvent', MikanVideoSourceClosedEvent);
  TypeRegistry.register('MikanVideoSourceModeChangedEvent', MikanVideoSourceModeChangedEvent);
  TypeRegistry.register('MikanVideoSourceOpenedEvent', MikanVideoSourceOpenedEvent);
  TypeRegistry.register('GetVideoSourceIntrinsics', GetVideoSourceIntrinsics);
  TypeRegistry.register('GetVideoSourceMode', GetVideoSourceMode);
  TypeRegistry.register('MikanVideoSourceIntrinsicsResponse', MikanVideoSourceIntrinsicsResponse);
  TypeRegistry.register('MikanVideoSourceModeResponse', MikanVideoSourceModeResponse);
  TypeRegistry.register('SetUSBVideoSourceDevice', SetUSBVideoSourceDevice);
  TypeRegistry.register('SetUSBVideoSourceFormat', SetUSBVideoSourceFormat);
  TypeRegistry.register('SetUSBVideoSourceFrameRate', SetUSBVideoSourceFrameRate);
  TypeRegistry.register('SetUSBVideoSourceResolution', SetUSBVideoSourceResolution);
  TypeRegistry.register('MikanBaseIntrinsics', MikanBaseIntrinsics);
  TypeRegistry.register('MikanDistortionCoefficients', MikanDistortionCoefficients);
  TypeRegistry.register('MikanMonoIntrinsics', MikanMonoIntrinsics);
  TypeRegistry.register('MikanNetworkVideoSourceValues', MikanNetworkVideoSourceValues);
  TypeRegistry.register('MikanStereoIntrinsics', MikanStereoIntrinsics);
  TypeRegistry.register('MikanUSBVideoSourceSystemValues', MikanUSBVideoSourceSystemValues);
  TypeRegistry.register('MikanUSBVideoSourceValues', MikanUSBVideoSourceValues);
  TypeRegistry.register('MikanVideoSourceIntrinsics', MikanVideoSourceIntrinsics);
  TypeRegistry.register('MikanVideoSourceValues', MikanVideoSourceValues);
}

// Auto-register when this module is first imported.
// Because this file is re-exported from types/index.ts -> bindings/index.ts,
// this call runs automatically the moment any symbol from @mikanxr/client is imported.
registerAllTypes();
