// This file is auto generated. DO NOT EDIT.

import { TypeRegistry } from '../Serialization/JsonDeserializer.js';
import { MikanResponse, MikanEvent, MikanRequest } from './MikanAPITypes.js';
import { MikanAnchorComponentValues, MikanAnchorSystemValues } from './MikanAnchorTypes.js';
import { MikanCameraNewFrameEvent } from './MikanCameraEvents.js';
import { AllocateCameraRenderTargetTextures, WriteCameraColorRenderTargetTexture, WriteCameraDepthRenderTargetTexture, PublishCameraRenderTargetTextures, FreeCameraRenderTargetTextures } from './MikanCameraRequests.js';
import { MikanCameraComponentValues } from './MikanCameraTypes.js';
import { MikanConnectedEvent, MikanDisconnectedEvent } from './MikanClientEvents.js';
import { InitClientRequest, DisposeClientRequest } from './MikanClientRequests.js';
import { MikanClientInfo } from './MikanClientTypes.js';
import { MikanComponentValues } from './MikanComponentTypes.js';
import { MikanCompositorComponentValues } from './MikanCompositorTypes.js';
import { MikanClientAPIVersion, MikanRenderTargetDescriptor } from './MikanCoreTypes.js';
import { MikanEditorSystemValues } from './MikanEditorTypes.js';
import { InvokeSystemFunctionRequest, InvokeComponentFunctionRequest, GetFunctionListRequest, FunctionDescriptorResponse } from './MikanFunctionRequests.js';
import { MikanFunctionDescriptor } from './MikanFunctionTypes.js';
import { ArucoMarkerImageResponse, GetArucoMarkerImageRequest } from './MikanMarkerRequests.js';
import { MikanMarkerSystemValues, MikanMarkerComponentValues } from './MikanMarkerTypes.js';
import { MikanMatrix4f, MikanVector3d, MikanMatrix3d, MikanMatrix4d, MikanRotator3f, MikanVector4f, MikanVector2i, MikanVector2f, MikanVector2d, MikanTransform, MikanVector3f, MikanVector4d, MikanMatrix4x3d, MikanQuatf, MikanQuatd } from './MikanMathTypes.js';
import { MikanPropertyUpdateEvent } from './MikanPropertyEvents.js';
import { SetPropertyNotifyMode, ComponentGetValuesResponse, SystemCreateObjectRequest, PropertySetValueRequest, GetComponentListRequest, ComponentGetValuesRequest, PropertyGetValueRequest, SystemGetValuesRequest, SystemDestroyObjectRequest, GetPropertyDescriptors, PropertySetValueResponse, PropertyGetValueResponse, ComponentListResponse, SystemGetValuesResponse, PropertyDescriptorResponse } from './MikanPropertyRequests.js';
import { MikanSystemValues, MikanPropertyDescriptor, MikanPropertyValue } from './MikanPropertyTypes.js';
import { MikanAppStageChangedEvent, MikanRemoteControlEvent } from './MikanRemoteControlEvents.js';
import { GetAppStageInfo, PopAppStage, MikanRemoteControlCommandResult, PushAppStage, MikanRemoteControlCommand, MikanAppStageInfoResponse } from './MikanRemoteControlRequest.js';
import { MikanAppStageInfo } from './MikanRemoteControlTypes.js';
import { MikanSceneSystemValues, MikanSceneComponentValues } from './MikanSceneTypes.js';
import { MikanScriptMessagePostedEvent } from './MikanScriptEvents.js';
import { InvokeComponentScriptTrigger, SendScriptMessage } from './MikanScriptRequest.js';
import { MikanScriptMessageInfo } from './MikanScriptTypes.js';
import { MikanStageComponentValues } from './MikanStageTypes.js';
import { GetModelStencilRenderGeometry, MikanStencilModelRenderGeometryResponse } from './MikanStencilRequest.js';
import { MikanModelStencilComponentValues, MikanQuadStencilSystemValues, MikanBoxStencilSystemValues, MikanModelStencilSystemValues, MikanStencilComponentValues, MikanQuadStencilComponentValues, MikanBoxStencilComponentValues, MikanTriagulatedMesh, MikanStencilModelRenderGeometry } from './MikanStencilTypes.js';
import { MikanTextureSourceOpenedEvent, MikanTextureSourceClosedEvent } from './MikanTextureSourceEvents.js';
import { MikanTextureSourceValues, MikanClientTextureSourceValues, MikanSpoutTextureSourceValues } from './MikanTextureSourceTypes.js';
import { MikanTrackingMountComponentValues } from './MikanTrackingMountTypes.js';
import { MikanVRTrackingVolumeComponentValues, MikanTrackingVolumeComponentValues, MikanMarkerTrackingVolumeComponentValues } from './MikanTrackingVolumeTypes.js';
import { MikanTransformComponentValues } from './MikanTransformTypes.js';
import { MikanVRDeviceComponentValues } from './MikanVRDeviceTypes.js';
import { MikanVector2fValue, MikanStringValue, MikanVariant, MikanIntArrayValue, MikanMatrix4fValue, MikanVariantBase, MikanBoolValue, MikanIntValue, MikanLongValue, MikanFloatValue, MikanDoubleValue, MikanVector3fValue, MikanVector4fValue, MikanQuatfValue, MikanVector2dValue, MikanVector3dValue, MikanVector4dValue, MikanQuatdValue, MikanBoolArrayValue, MikanFloatArrayValue, MikanStringArrayValue, MikanStringMapValue } from './MikanVariantTypes.js';
import { MikanVideoSourceOpenedEvent, MikanVideoSourceClosedEvent, MikanVideoSourceModeChangedEvent } from './MikanVideoSourceEvents.js';
import { SetUSBVideoSourceDevice, SetUSBVideoSourceFormat, SetUSBVideoSourceFrameRate, MikanVideoSourceModeResponse, GetVideoSourceMode, GetVideoSourceIntrinsics, SetUSBVideoSourceResolution, MikanVideoSourceIntrinsicsResponse } from './MikanVideoSourceRequest.js';
import { MikanUSBVideoSourceValues, MikanNetworkVideoSourceValues, MikanDistortionCoefficients, MikanBaseIntrinsics, MikanMonoIntrinsics, MikanStereoIntrinsics, MikanVideoSourceIntrinsics, MikanVideoSourceValues, MikanUSBVideoSourceSystemValues } from './MikanVideoSourceTypes.js';

export function registerAllTypes(): void {
  TypeRegistry.register('MikanResponse', MikanResponse);
  TypeRegistry.register('MikanEvent', MikanEvent);
  TypeRegistry.register('MikanRequest', MikanRequest);
  TypeRegistry.register('MikanAnchorComponentValues', MikanAnchorComponentValues);
  TypeRegistry.register('MikanAnchorSystemValues', MikanAnchorSystemValues);
  TypeRegistry.register('MikanCameraNewFrameEvent', MikanCameraNewFrameEvent);
  TypeRegistry.register('AllocateCameraRenderTargetTextures', AllocateCameraRenderTargetTextures);
  TypeRegistry.register('WriteCameraColorRenderTargetTexture', WriteCameraColorRenderTargetTexture);
  TypeRegistry.register('WriteCameraDepthRenderTargetTexture', WriteCameraDepthRenderTargetTexture);
  TypeRegistry.register('PublishCameraRenderTargetTextures', PublishCameraRenderTargetTextures);
  TypeRegistry.register('FreeCameraRenderTargetTextures', FreeCameraRenderTargetTextures);
  TypeRegistry.register('MikanCameraComponentValues', MikanCameraComponentValues);
  TypeRegistry.register('MikanConnectedEvent', MikanConnectedEvent);
  TypeRegistry.register('MikanDisconnectedEvent', MikanDisconnectedEvent);
  TypeRegistry.register('InitClientRequest', InitClientRequest);
  TypeRegistry.register('DisposeClientRequest', DisposeClientRequest);
  TypeRegistry.register('MikanClientInfo', MikanClientInfo);
  TypeRegistry.register('MikanComponentValues', MikanComponentValues);
  TypeRegistry.register('MikanCompositorComponentValues', MikanCompositorComponentValues);
  TypeRegistry.register('MikanClientAPIVersion', MikanClientAPIVersion);
  TypeRegistry.register('MikanRenderTargetDescriptor', MikanRenderTargetDescriptor);
  TypeRegistry.register('MikanEditorSystemValues', MikanEditorSystemValues);
  TypeRegistry.register('InvokeSystemFunctionRequest', InvokeSystemFunctionRequest);
  TypeRegistry.register('InvokeComponentFunctionRequest', InvokeComponentFunctionRequest);
  TypeRegistry.register('GetFunctionListRequest', GetFunctionListRequest);
  TypeRegistry.register('FunctionDescriptorResponse', FunctionDescriptorResponse);
  TypeRegistry.register('MikanFunctionDescriptor', MikanFunctionDescriptor);
  TypeRegistry.register('ArucoMarkerImageResponse', ArucoMarkerImageResponse);
  TypeRegistry.register('GetArucoMarkerImageRequest', GetArucoMarkerImageRequest);
  TypeRegistry.register('MikanMarkerSystemValues', MikanMarkerSystemValues);
  TypeRegistry.register('MikanMarkerComponentValues', MikanMarkerComponentValues);
  TypeRegistry.register('MikanMatrix4f', MikanMatrix4f);
  TypeRegistry.register('MikanVector3d', MikanVector3d);
  TypeRegistry.register('MikanMatrix3d', MikanMatrix3d);
  TypeRegistry.register('MikanMatrix4d', MikanMatrix4d);
  TypeRegistry.register('MikanRotator3f', MikanRotator3f);
  TypeRegistry.register('MikanVector4f', MikanVector4f);
  TypeRegistry.register('MikanVector2i', MikanVector2i);
  TypeRegistry.register('MikanVector2f', MikanVector2f);
  TypeRegistry.register('MikanVector2d', MikanVector2d);
  TypeRegistry.register('MikanTransform', MikanTransform);
  TypeRegistry.register('MikanVector3f', MikanVector3f);
  TypeRegistry.register('MikanVector4d', MikanVector4d);
  TypeRegistry.register('MikanMatrix4x3d', MikanMatrix4x3d);
  TypeRegistry.register('MikanQuatf', MikanQuatf);
  TypeRegistry.register('MikanQuatd', MikanQuatd);
  TypeRegistry.register('MikanPropertyUpdateEvent', MikanPropertyUpdateEvent);
  TypeRegistry.register('SetPropertyNotifyMode', SetPropertyNotifyMode);
  TypeRegistry.register('ComponentGetValuesResponse', ComponentGetValuesResponse);
  TypeRegistry.register('SystemCreateObjectRequest', SystemCreateObjectRequest);
  TypeRegistry.register('PropertySetValueRequest', PropertySetValueRequest);
  TypeRegistry.register('GetComponentListRequest', GetComponentListRequest);
  TypeRegistry.register('ComponentGetValuesRequest', ComponentGetValuesRequest);
  TypeRegistry.register('PropertyGetValueRequest', PropertyGetValueRequest);
  TypeRegistry.register('SystemGetValuesRequest', SystemGetValuesRequest);
  TypeRegistry.register('SystemDestroyObjectRequest', SystemDestroyObjectRequest);
  TypeRegistry.register('GetPropertyDescriptors', GetPropertyDescriptors);
  TypeRegistry.register('PropertySetValueResponse', PropertySetValueResponse);
  TypeRegistry.register('PropertyGetValueResponse', PropertyGetValueResponse);
  TypeRegistry.register('ComponentListResponse', ComponentListResponse);
  TypeRegistry.register('SystemGetValuesResponse', SystemGetValuesResponse);
  TypeRegistry.register('PropertyDescriptorResponse', PropertyDescriptorResponse);
  TypeRegistry.register('MikanSystemValues', MikanSystemValues);
  TypeRegistry.register('MikanPropertyDescriptor', MikanPropertyDescriptor);
  TypeRegistry.register('MikanPropertyValue', MikanPropertyValue);
  TypeRegistry.register('MikanAppStageChangedEvent', MikanAppStageChangedEvent);
  TypeRegistry.register('MikanRemoteControlEvent', MikanRemoteControlEvent);
  TypeRegistry.register('GetAppStageInfo', GetAppStageInfo);
  TypeRegistry.register('PopAppStage', PopAppStage);
  TypeRegistry.register('MikanRemoteControlCommandResult', MikanRemoteControlCommandResult);
  TypeRegistry.register('PushAppStage', PushAppStage);
  TypeRegistry.register('MikanRemoteControlCommand', MikanRemoteControlCommand);
  TypeRegistry.register('MikanAppStageInfoResponse', MikanAppStageInfoResponse);
  TypeRegistry.register('MikanAppStageInfo', MikanAppStageInfo);
  TypeRegistry.register('MikanSceneSystemValues', MikanSceneSystemValues);
  TypeRegistry.register('MikanSceneComponentValues', MikanSceneComponentValues);
  TypeRegistry.register('MikanScriptMessagePostedEvent', MikanScriptMessagePostedEvent);
  TypeRegistry.register('InvokeComponentScriptTrigger', InvokeComponentScriptTrigger);
  TypeRegistry.register('SendScriptMessage', SendScriptMessage);
  TypeRegistry.register('MikanScriptMessageInfo', MikanScriptMessageInfo);
  TypeRegistry.register('MikanStageComponentValues', MikanStageComponentValues);
  TypeRegistry.register('GetModelStencilRenderGeometry', GetModelStencilRenderGeometry);
  TypeRegistry.register('MikanStencilModelRenderGeometryResponse', MikanStencilModelRenderGeometryResponse);
  TypeRegistry.register('MikanModelStencilComponentValues', MikanModelStencilComponentValues);
  TypeRegistry.register('MikanQuadStencilSystemValues', MikanQuadStencilSystemValues);
  TypeRegistry.register('MikanBoxStencilSystemValues', MikanBoxStencilSystemValues);
  TypeRegistry.register('MikanModelStencilSystemValues', MikanModelStencilSystemValues);
  TypeRegistry.register('MikanStencilComponentValues', MikanStencilComponentValues);
  TypeRegistry.register('MikanQuadStencilComponentValues', MikanQuadStencilComponentValues);
  TypeRegistry.register('MikanBoxStencilComponentValues', MikanBoxStencilComponentValues);
  TypeRegistry.register('MikanTriagulatedMesh', MikanTriagulatedMesh);
  TypeRegistry.register('MikanStencilModelRenderGeometry', MikanStencilModelRenderGeometry);
  TypeRegistry.register('MikanTextureSourceOpenedEvent', MikanTextureSourceOpenedEvent);
  TypeRegistry.register('MikanTextureSourceClosedEvent', MikanTextureSourceClosedEvent);
  TypeRegistry.register('MikanTextureSourceValues', MikanTextureSourceValues);
  TypeRegistry.register('MikanClientTextureSourceValues', MikanClientTextureSourceValues);
  TypeRegistry.register('MikanSpoutTextureSourceValues', MikanSpoutTextureSourceValues);
  TypeRegistry.register('MikanTrackingMountComponentValues', MikanTrackingMountComponentValues);
  TypeRegistry.register('MikanVRTrackingVolumeComponentValues', MikanVRTrackingVolumeComponentValues);
  TypeRegistry.register('MikanTrackingVolumeComponentValues', MikanTrackingVolumeComponentValues);
  TypeRegistry.register('MikanMarkerTrackingVolumeComponentValues', MikanMarkerTrackingVolumeComponentValues);
  TypeRegistry.register('MikanTransformComponentValues', MikanTransformComponentValues);
  TypeRegistry.register('MikanVRDeviceComponentValues', MikanVRDeviceComponentValues);
  TypeRegistry.register('MikanVector2fValue', MikanVector2fValue);
  TypeRegistry.register('MikanStringValue', MikanStringValue);
  TypeRegistry.register('MikanVariant', MikanVariant);
  TypeRegistry.register('MikanIntArrayValue', MikanIntArrayValue);
  TypeRegistry.register('MikanMatrix4fValue', MikanMatrix4fValue);
  TypeRegistry.register('MikanVariantBase', MikanVariantBase);
  TypeRegistry.register('MikanBoolValue', MikanBoolValue);
  TypeRegistry.register('MikanIntValue', MikanIntValue);
  TypeRegistry.register('MikanLongValue', MikanLongValue);
  TypeRegistry.register('MikanFloatValue', MikanFloatValue);
  TypeRegistry.register('MikanDoubleValue', MikanDoubleValue);
  TypeRegistry.register('MikanVector3fValue', MikanVector3fValue);
  TypeRegistry.register('MikanVector4fValue', MikanVector4fValue);
  TypeRegistry.register('MikanQuatfValue', MikanQuatfValue);
  TypeRegistry.register('MikanVector2dValue', MikanVector2dValue);
  TypeRegistry.register('MikanVector3dValue', MikanVector3dValue);
  TypeRegistry.register('MikanVector4dValue', MikanVector4dValue);
  TypeRegistry.register('MikanQuatdValue', MikanQuatdValue);
  TypeRegistry.register('MikanBoolArrayValue', MikanBoolArrayValue);
  TypeRegistry.register('MikanFloatArrayValue', MikanFloatArrayValue);
  TypeRegistry.register('MikanStringArrayValue', MikanStringArrayValue);
  TypeRegistry.register('MikanStringMapValue', MikanStringMapValue);
  TypeRegistry.register('MikanVideoSourceOpenedEvent', MikanVideoSourceOpenedEvent);
  TypeRegistry.register('MikanVideoSourceClosedEvent', MikanVideoSourceClosedEvent);
  TypeRegistry.register('MikanVideoSourceModeChangedEvent', MikanVideoSourceModeChangedEvent);
  TypeRegistry.register('SetUSBVideoSourceDevice', SetUSBVideoSourceDevice);
  TypeRegistry.register('SetUSBVideoSourceFormat', SetUSBVideoSourceFormat);
  TypeRegistry.register('SetUSBVideoSourceFrameRate', SetUSBVideoSourceFrameRate);
  TypeRegistry.register('MikanVideoSourceModeResponse', MikanVideoSourceModeResponse);
  TypeRegistry.register('GetVideoSourceMode', GetVideoSourceMode);
  TypeRegistry.register('GetVideoSourceIntrinsics', GetVideoSourceIntrinsics);
  TypeRegistry.register('SetUSBVideoSourceResolution', SetUSBVideoSourceResolution);
  TypeRegistry.register('MikanVideoSourceIntrinsicsResponse', MikanVideoSourceIntrinsicsResponse);
  TypeRegistry.register('MikanUSBVideoSourceValues', MikanUSBVideoSourceValues);
  TypeRegistry.register('MikanNetworkVideoSourceValues', MikanNetworkVideoSourceValues);
  TypeRegistry.register('MikanDistortionCoefficients', MikanDistortionCoefficients);
  TypeRegistry.register('MikanBaseIntrinsics', MikanBaseIntrinsics);
  TypeRegistry.register('MikanMonoIntrinsics', MikanMonoIntrinsics);
  TypeRegistry.register('MikanStereoIntrinsics', MikanStereoIntrinsics);
  TypeRegistry.register('MikanVideoSourceIntrinsics', MikanVideoSourceIntrinsics);
  TypeRegistry.register('MikanVideoSourceValues', MikanVideoSourceValues);
  TypeRegistry.register('MikanUSBVideoSourceSystemValues', MikanUSBVideoSourceSystemValues);
}

// Auto-register when this module is first imported.
// Because this file is re-exported from types/index.ts -> bindings/index.ts,
// this call runs automatically the moment any symbol from @mikanxr/client is imported.
registerAllTypes();
