//-- includes -----
#include "NodeEditorWindow.h"
#include "Logger.h"
#include "MkGuiContext.h"
#include "MkGuiScopedStyle.h"
#include "MkGuiStyleManager.h"
#include "MkGuiScopedUpdate.h"
#include "MkGuiScopedContext.h"
#include "MkGuiScopedChild.h"
#include "MkGuiScopedWindow.h"
#include "MkGuiScopedGroup.h"
#include "MkGuiScopedPopup.h"
#include "MkGuiScopedDragDropSource.h"
#include "MkGuiScopedDragDropTarget.h"
#include "MkGuiDockspace.h"
#include "MkCanvasScopedEditor.h"

#include "App.h"
#include "AssetReference.h"
#include "IMkGraphicsContext.h"
#include "MikanModelResourceManager.h"
#include "IMkViewport.h"
#include "MkStateStack.h"
#include "IMkState.h"
#include "MkStateModifiers.h"
#include "MkWindowEvent.h"
#include "IMkTexture.h"
#include "Graphs/NodeGraph.h"
#include "Graphs/NodeEvaluator.h"
#include "Nodes/Node.h"
#include "LocText.h"
#include "MkGuiDrawUtils.h"
#include "PathUtils.h"
#include "ProjectConfig.h"
#include "ProjectManager.h"
#include "StringUtils.h"
#include "TextStyle.h"

#include "Pins/NodeLink.h"
#include "Pins/NodePin.h"

#include "imgui.h"
#include "imgui_node_editor.h"

// Autogenerated header containing Unicode Icon IDs from "forkawesome-webfont.ttf"
#include "IconsForkAwesome.h"

#include "tinyfiledialogs.h" // Cross-platform file dialogs library

#include <easy/profiler.h>

#include <cfloat>
#include <typeinfo>

#include "glm/ext/vector_float4.hpp"

namespace ed= ax::NodeEditor;

// Drag-Drop Payload Types
#define DRAG_DROP_TYPE_VARIABLE "Variable"
#define DRAG_DROP_TYPE_ASSET_REF "Asset"

// Truncate UTF-8 text to fit maxWidth in the current font, appending an ellipsis
static std::string truncateTextWithEllipsis(const std::string& text, float maxWidth)
{
	if (ImGui::CalcTextSize(text.c_str()).x <= maxWidth)
	{
		return text;
	}

	std::string truncated= text;
	while (!truncated.empty() && ImGui::CalcTextSize((truncated + "...").c_str()).x > maxWidth)
	{
		// Pop one codepoint (skip UTF-8 continuation bytes)
		truncated.pop_back();
		while (!truncated.empty() && ((unsigned char)truncated.back() & 0xC0) == 0x80)
		{
			truncated.pop_back();
		}
	}

	return truncated + "...";
}

//-- public methods -----
NodeEditorWindow::NodeEditorWindow(App* ownerApp)
	: EditorWindow(ownerApp)
{
	shareGraphicsContextWithMainWindow();
}

NodeEditorWindow::~NodeEditorWindow() {}

// -- IEditorWindow ----
bool NodeEditorWindow::startup()
{
	EASY_FUNCTION();

	bool success= true;

	MIKAN_LOG_INFO("NodeEditorWindow::init()") << "Initializing NodeEditorWindow";

	static const int k_node_window_pixel_width= 1080;
	static const int k_node_window_pixel_height= 720;

	if (success && !startupWindow(locText("windows.nodeEditor"), k_node_window_pixel_width, k_node_window_pixel_height))
	{
		success= false;
	}

	if (success && !startupGuiContext("node_editor", /*bEnableDocking=*/true))
	{
		success= false;
	}

	if (success && !startupStyleManager())
	{
		success= false;
	}

	if (success)
	{
		m_editorState.styleManager= m_styleManager.get();
	}

	if (success)
	{
		// The canvas context must be created while this window's ImGui context
		// is current, since the library binds to ImGui::GetCurrentContext()
		MkGuiScopedContext scopedContext(*m_guiContext.get());

		m_canvasContext= MkCanvas::createEditorContext();
		success= (m_canvasContext != nullptr);
		if (success)
		{
			MkCanvas::applyEditorStyle(m_canvasContext);
		}
	}

	if (success && !startupTextureCache())
	{
		success= false;
	}

	if (success && !startupModelResourceManager())
	{
		success= false;
	}

	return success;
}

void NodeEditorWindow::update(float deltaSeconds)
{
	EASY_FUNCTION();

	// Run parked automation work and scheduled history steps outside the
	// ImGui frame, where graph rebuilds and context pushes are safe
	flushAutomationTasks();
	if (m_pendingHistorySteps != 0)
	{
		const int steps= m_pendingHistorySteps;
		m_pendingHistorySteps= 0;
		stepHistory(steps);
	}

	// Push the ImGui Update scope
	MkGuiScopedUpdate scopedCtx(*m_guiContext);

	// Process most recent SDL events (keyboard, mouse, etc)
	m_mkWindowContext->handleEvents(this);

	// Process UI input and build ImGui draw lists
	updateUI();

	// On Pop: Finalize draw lists and clear ImGui context
}

void NodeEditorWindow::render()
{
	EASY_FUNCTION();

	// Clear the window
	m_graphicsContext->renderBegin();

	{
		// Create a scoped UI rendering settings
		MkScopedState scopedState= m_graphicsContext->getMkStateStack().createScopedState("appStage renderUI");
		IMkState* glState= scopedState.getStackState();

		mkStateSetViewport(glState, 0, 0, (int)m_mkWindowContext->getWidth(), (int)m_mkWindowContext->getHeight());

		// Submit the MkGui draw calls
		m_guiContext->submitDrawData();
	}

	// Finalize rendering
	m_graphicsContext->renderEnd();

	// Present the rendered frame
	m_mkWindowContext->present();
}

void NodeEditorWindow::updateUI()
{
	MkGuiScopedStyle baseStyle(m_styleManager->getStyle("node_editor_base"));

	bool bNeedsDefaultLayout= false;
	const ImGuiID dockspaceId=
		MkGui::beginDockspaceHost("##NodeEditorDockHost", "NodeEditorDockspace", bNeedsDefaultLayout);
	if (bNeedsDefaultLayout)
	{
		buildDefaultDockLayout((unsigned int)dockspaceId);
		MkGui::dockBuilderFinish(dockspaceId);
	}

	if (ImGui::BeginMenuBar())
	{
		renderMenuBar();
		ImGui::EndMenuBar();
	}

	// Each panel is its own dockable window; the View menu toggles all but the graph
	{
		MkGuiScopedWindow graphWindow(locWindowTitle("windows.nodeGraphPanel"));
		if (graphWindow)
		{
			renderMainFrame();
		}
	}

	if (m_bShowVariablesPanel)
	{
		MkGuiScopedWindow variablesWindow(locWindowTitle("windows.nodeVariablesPanel"), &m_bShowVariablesPanel);
		if (variablesWindow)
		{
			renderGraphVariablesPanel();
		}
	}

	if (m_bShowAssetsPanel)
	{
		MkGuiScopedWindow assetsWindow(locWindowTitle("windows.nodeAssetsPanel"), &m_bShowAssetsPanel);
		if (assetsWindow)
		{
			renderAssetsPanel();
		}
	}

	if (m_bShowDetailsPanel)
	{
		MkGuiScopedWindow detailsWindow(locWindowTitle("windows.nodeDetailsPanel"), &m_bShowDetailsPanel);
		if (detailsWindow)
		{
			renderSelectedObjectPanel();
		}
	}

	MkGui::endDockspaceHost();

	// Keyboard chords; text fields keep ImGui's own undo
	const ImGuiIO& io= ImGui::GetIO();
	if (ImGui::IsKeyPressed(ImGuiKey_Z, false) && io.KeyCtrl && !ImGui::IsAnyItemActive())
	{
		if (io.KeyShift)
		{
			redo();
		}
		else
		{
			undo();
		}
	}
	if (ImGui::IsKeyPressed(ImGuiKey_S, false) && io.KeyCtrl && !ImGui::IsAnyItemActive())
	{
		saveGraph(false);
	}

	updateHistoryCapture();
}

void NodeEditorWindow::renderMenuBar()
{
	if (ImGui::BeginMenu(locLabel("mainWindow.fileMenu")))
	{
		if (ImGui::MenuItem(locLabel("nodeEditor.save"), "Ctrl+S"))
		{
			saveGraph(false);
		}
		if (ImGui::MenuItem(locLabel("nodeEditor.saveAs")))
		{
			saveGraph(true);
		}
		ImGui::EndMenu();
	}

	if (ImGui::BeginMenu(locLabel("nodeEditor.editMenu")))
	{
		if (ImGui::MenuItem(locLabel("nodeEditor.undo"), "Ctrl+Z", false, canUndo()))
		{
			undo();
		}
		if (ImGui::MenuItem(locLabel("nodeEditor.redo"), "Ctrl+Shift+Z", false, canRedo()))
		{
			redo();
		}
		ImGui::EndMenu();
	}

	if (ImGui::BeginMenu(locLabel("mainWindow.viewMenu")))
	{
		ImGui::MenuItem(locLabel("nodeEditor.variables"), nullptr, &m_bShowVariablesPanel);
		ImGui::MenuItem(locLabel("nodeEditor.assetsTab"), nullptr, &m_bShowAssetsPanel);
		ImGui::MenuItem(locLabel("nodeEditor.details"), nullptr, &m_bShowDetailsPanel);
		ImGui::EndMenu();
	}

	renderMenuBarExtras();
}

void NodeEditorWindow::buildDefaultDockLayout(unsigned int dockspaceId)
{
	ImGuiID remaining= (ImGuiID)dockspaceId;
	const ImGuiID leftId= MkGui::dockBuilderSplit(remaining, ImGuiDir_Left, 0.18f, remaining);
	const ImGuiID rightId= MkGui::dockBuilderSplit(remaining, ImGuiDir_Right, 0.25f, remaining);
	const ImGuiID bottomId= MkGui::dockBuilderSplit(remaining, ImGuiDir_Down, 0.28f, remaining);

	MkGui::dockBuilderDockWindow(locWindowTitle("windows.nodeVariablesPanel"), leftId);
	MkGui::dockBuilderDockWindow(locWindowTitle("windows.nodeDetailsPanel"), rightId);
	MkGui::dockBuilderDockWindow(locWindowTitle("windows.nodeAssetsPanel"), bottomId);
	MkGui::dockBuilderDockWindow(locWindowTitle("windows.nodeGraphPanel"), remaining);
}

void NodeEditorWindow::renderMainFrame()
{
	NodeGraphPtr nodeGraph= getNodeGraph();

	// Interaction results gathered inside the canvas scope but acted on after
	// it closes: popups and graph mutations stay out of the canvas transform
	bool bOpenNodeMenu= false;
	bool bOpenLinkMenu= false;
	bool bOpenBackgroundMenu= false;
	struct PendingLinkCreate
	{
		int startPinId;
		int endPinId;
	};
	std::vector<PendingLinkCreate> pendingLinkCreates;
	std::vector<t_node_link_id> pendingLinkDeletes;
	std::vector<t_node_id> pendingNodeDeletes;
	std::vector<ImVec2> evalErrorScreenPositions;

	{
		MkCanvasScopedEditor scopedEditor(m_canvasContext, "GraphCanvas");

		if (nodeGraph)
		{
			nodeGraph->editorRender(m_editorState);
		}

		// Inside Begin/End the canvas remaps io.MousePos into canvas space, so
		// the raw mouse position is already the node-placement position
		const ImVec2 mouseCanvasPos= ImGui::GetMousePos();

		// Track the drop position while an asset/variable drag is in flight
		// (onNodeCreated places new nodes from hangPosGridSpace)
		if (ImGui::GetDragDropPayload() != nullptr)
		{
			m_editorState.hangPosGridSpace= mouseCanvasPos;
		}

		// Link creation, with live accept/reject feedback from pin compatibility.
		//
		// EndCreate() is only legal after a BeginCreate() that returned true: the
		// action only marks itself active once it has a drag to report, and its
		// End() asserts on that flag rather than tolerating the unpaired call.
		// Calling it unconditionally therefore fires on every frame that is not
		// mid-drag, which is nearly all of them. It went unnoticed because
		// IM_ASSERT is assert(), so only a debug build trips it.
		const bool bCreateStarted= ed::BeginCreate();
		if (bCreateStarted)
		{
			ed::PinId startPinId, endPinId;
			ed::PinId hangPinId;
			if (ed::QueryNewLink(&startPinId, &endPinId))
			{
				const int startGraphPinId= MkCanvas::fromCanvasId((int)startPinId.Get());
				const int endGraphPinId= MkCanvas::fromCanvasId((int)endPinId.Get());
				m_editorState.startedLinkPinId= startGraphPinId;

				NodePinPtr startPin= nodeGraph ? nodeGraph->getPinById(startGraphPinId) : NodePinPtr();
				NodePinPtr endPin= nodeGraph ? nodeGraph->getPinById(endGraphPinId) : NodePinPtr();
				if (startPin && endPin && startPin->canPinsBeConnected(endPin))
				{
					const ImVec4 previewColor= ImGui::ColorConvertU32ToFloat4(startPin->editorGetLinkStyleColor());
					if (ed::AcceptNewItem(previewColor, 3.f))
					{
						pendingLinkCreates.push_back({startGraphPinId, endGraphPinId});
					}
				}
				else
				{
					ed::RejectNewItem(ImVec4(1.f, 0.25f, 0.25f, 1.f), 3.f);
				}
			}
			else if (ed::QueryNewNode(&hangPinId))
			{
				m_editorState.startedLinkPinId= MkCanvas::fromCanvasId((int)hangPinId.Get());

				if (ed::AcceptNewItem())
				{
					// Link dropped on empty canvas: offer node creation there
					m_editorState.bLinkHanged= true;
					m_editorState.hangPosGridSpace= mouseCanvasPos;
					bOpenBackgroundMenu= true;
				}
			}
		}
		else if (!m_editorState.bLinkHanged)
		{
			m_editorState.startedLinkPinId= -1;
		}

		if (bCreateStarted)
		{
			ed::EndCreate();
		}

		// Deletion funnel: the canvas's Del-key and programmatic deletions all
		// arrive here, gated by each node's editorCanDelete
		if (ed::BeginDelete())
		{
			ed::LinkId deletedLinkId;
			while (ed::QueryDeletedLink(&deletedLinkId))
			{
				if (ed::AcceptDeletedItem())
				{
					pendingLinkDeletes.push_back(MkCanvas::fromCanvasId((int)deletedLinkId.Get()));
				}
			}

			ed::NodeId deletedNodeId;
			while (ed::QueryDeletedNode(&deletedNodeId))
			{
				const t_node_id deletedGraphNodeId= MkCanvas::fromCanvasId((int)deletedNodeId.Get());
				NodePtr node= nodeGraph ? nodeGraph->getNodeById(deletedGraphNodeId) : NodePtr();
				if (node && node->editorCanDelete())
				{
					if (ed::AcceptDeletedItem())
					{
						pendingNodeDeletes.push_back(deletedGraphNodeId);
					}
				}
				else
				{
					ed::RejectDeletedItem();
				}
			}
		}
		ed::EndDelete();

		// Node selection sync (filtered against the graph so ids from deleted
		// nodes never linger in the selection)
		if (nodeGraph)
		{
			std::vector<ed::NodeId> selectedNodeIds(ed::GetSelectedObjectCount());
			const int selectedNodeCount= ed::GetSelectedNodes(selectedNodeIds.data(), (int)selectedNodeIds.size());
			std::vector<t_node_id> liveNodeIds;
			for (int index= 0; index < selectedNodeCount; index++)
			{
				const t_node_id nodeId= MkCanvas::fromCanvasId((int)selectedNodeIds[index].Get());
				if (nodeGraph->getNodeById(nodeId))
				{
					liveNodeIds.push_back(nodeId);
				}
			}

			if (!liveNodeIds.empty())
			{
				GraphObjectSelection selection(GraphObjectIdType::NODE, (int)liveNodeIds.size());
				for (int index= 0; index < (int)liveNodeIds.size(); index++)
				{
					selection.setObjectId(index, liveNodeIds[index]);
				}
				m_objectSelection= selection;
			}
		}

		// Context menu queries; popups open after the canvas closes
		ed::NodeId contextNodeId;
		ed::LinkId contextLinkId;
		if (ed::ShowNodeContextMenu(&contextNodeId))
		{
			m_objectSelection= GraphObjectSelection(GraphObjectIdType::NODE, 1);
			m_objectSelection.setObjectId(0, MkCanvas::fromCanvasId((int)contextNodeId.Get()));
			ed::SelectNode(contextNodeId);
			bOpenNodeMenu= true;
		}
		else if (ed::ShowLinkContextMenu(&contextLinkId))
		{
			m_objectSelection= GraphObjectSelection(GraphObjectIdType::LINK, 1);
			m_objectSelection.setObjectId(0, MkCanvas::fromCanvasId((int)contextLinkId.Get()));
			ed::SelectLink(contextLinkId);
			bOpenLinkMenu= true;
		}
		else if (ed::ShowBackgroundContextMenu())
		{
			m_editorState.hangPosGridSpace= mouseCanvasPos;
			bOpenBackgroundMenu= true;
		}

		// Eval error overlay anchors (canvas to screen while the canvas is current)
		for (const NodeEvaluationError& evalError : m_lastNodeEvalErrors)
		{
			ImVec2 screenPos(0.f, 0.f);
			if (evalError.errorNodeId != -1)
			{
				screenPos= ed::CanvasToScreen(ed::GetNodePosition(MkCanvas::toCanvasId(evalError.errorNodeId)));
			}
			evalErrorScreenPositions.push_back(screenPos);
		}
	}

	// Drag and drop creation: the canvas child is the last submitted item, so
	// the drop target must attach before any other item renders
	handleMainFrameDragDrop(m_editorState);

	// Apply the gathered graph mutations
	if (nodeGraph)
	{
		for (const PendingLinkCreate& linkCreate : pendingLinkCreates)
		{
			m_editorState.startedLinkPinId= -1;
			nodeGraph->createLink(linkCreate.startPinId, linkCreate.endPinId);
		}
		for (t_node_link_id linkId : pendingLinkDeletes)
		{
			nodeGraph->deleteLinkById(linkId);
		}
		for (t_node_id nodeId : pendingNodeDeletes)
		{
			nodeGraph->deleteNodeById(nodeId);
		}
	}

	// Draw error messages on top of related nodes
	renderNodeEvalErrors(evalErrorScreenPositions);

	// Context menu popups
	if (bOpenNodeMenu)
	{
		ImGui::OpenPopup("editor_context_menu_node");
	}
	else if (bOpenLinkMenu)
	{
		ImGui::OpenPopup("editor_context_menu_link");
	}
	else if (bOpenBackgroundMenu)
	{
		ImGui::OpenPopup("editor_context_menu_nodes");
	}
	renderMainFrameContextMenu(m_editorState);
}

void NodeEditorWindow::renderNodeEvalErrors(const std::vector<ImVec2>& errorScreenPositions)
{
	if (m_editorState.nodeGraph && m_lastNodeEvalErrors.size() > 0)
	{
		size_t errorIter= 0;
		while (errorIter < m_lastNodeEvalErrors.size())
		{
			const NodeEvaluationError* currentError= &m_lastNodeEvalErrors[errorIter];
			const std::string evalWindowId=
				StringUtils::stringify(locText("nodeEditor.evalErrorWindowTitle"), "##Node", currentError->errorNodeId);

			static const float k_errorWindowOffset= 50.f;
			ImVec2 errorPos= errorIter < errorScreenPositions.size() ? errorScreenPositions[errorIter] : ImVec2(0, 0);
			errorPos.y-= k_errorWindowOffset;

			ImGui::SetNextWindowPos(errorPos);
			MkGuiScopedWindow evalWindow(evalWindowId.c_str(), nullptr,
										 ImGuiWindowFlags_NoResize | ImGuiWindowFlags_AlwaysAutoResize
											 | ImGuiWindowFlags_NoNav);
			{
				MkGuiScopedGroup errorGroup;
				MkGuiScopedStyle errorTextStyle(m_styleManager->getStyle("node_editor_error_text"));
				while (errorIter < m_lastNodeEvalErrors.size())
				{
					// Add a bullet point for each error on the same node
					ImGui::BulletText("%s", currentError->errorMessage.c_str());

					// Advance to the next error message on this node
					errorIter++;

					// If the next error is on a different node, move on to the next error window
					if (errorIter < m_lastNodeEvalErrors.size())
					{
						const NodeEvaluationError* nextError= &m_lastNodeEvalErrors[errorIter];

						if (nextError->errorNodeId == currentError->errorNodeId)
						{
							currentError= nextError;
						}
						else
						{
							break;
						}
					}
				}
			}
		}
	}
}

void NodeEditorWindow::renderMainFrameContextMenu(const NodeEditorState& editorState)
{
	// The canvas hover queries in renderMainFrame decide which popup opened;
	// this only renders whichever one is active
	MkGuiScopedStyle contextMenuStyle(m_styleManager->getStyle("node_editor_context_menu"));
	{
		MkGuiScopedPopup nodePopup("editor_context_menu_node");
		if (nodePopup)
		{
			NodePtr node;
			if (m_objectSelection.getObjectIdType() == GraphObjectIdType::NODE)
			{
				node= getNodeGraph()->getNodeById(m_objectSelection.getObjectId(0));
			}

			if (node && node->editorCanDelete())
			{
				if (ImGui::MenuItem(locLabel("nodeEditor.delete"), ICON_FK_TRASH, "DELETE"))
				{
					getNodeGraph()->deleteNodeById(m_objectSelection.getObjectId(0));
				}
			}
			else
			{
				ImGui::CloseCurrentPopup();
			}
		}
		else
		{
			MkGuiScopedPopup linkPopup("editor_context_menu_link");
			if (linkPopup)
			{
				if (m_objectSelection.getObjectIdType() == GraphObjectIdType::LINK
					&& ImGui::MenuItem(locLabel("nodeEditor.delete"), ICON_FK_TRASH, "DELETE"))
				{
					getNodeGraph()->deleteLinkById(m_objectSelection.getObjectId(0));
				}
			}
			else
			{
				MkGuiScopedPopup nodesPopup("editor_context_menu_nodes");
				if (nodesPopup)
				{
					NodeGraphPtr nodeGraph= getNodeGraph();
					if (nodeGraph)
					{
						std::vector<NodeFactoryPtr> nodeFactories=
							getNodeGraph()->editorGetValidNodeFactories(editorState);
						for (NodeFactoryPtr nodeFactory : nodeFactories)
						{
							const std::string nodeTitle= nodeFactory->getNodeDefaultObject()->editorGetTitle();

							if (ImGui::MenuItem(nodeTitle.c_str()))
							{
								getNodeGraph()->createNode(nodeFactory, editorState);
								break;
							}
						}
					}
				}
				else if (m_editorState.bLinkHanged)
				{
					m_editorState.bLinkHanged= false;
					m_editorState.startedLinkPinId= -1;
				}
			}
		}
	}
}

void NodeEditorWindow::renderGraphVariablesPanel()
{
	{
		MkGuiScopedStyle selectionStyle(m_styleManager->getStyle("node_editor_variable_list"));

		// A reorder mutates sort orders, so the drop is applied after the list
		// has finished rendering
		t_graph_property_id pendingReorderMovedId= -1;
		t_graph_property_id pendingReorderTargetId= -1;

		std::vector<GraphPropertyPtr> sortedProperties= getNodeGraph()->getPropertiesInSortOrder();
		for (GraphPropertyPtr variable : sortedProperties)
		{
			const t_graph_property_id propertyId= variable->getId();

			// Variable
			const std::string varIcon= variable->editorGetIcon();
			const ImVec4& variconColor= variable->editorGetIconColor();
			ImGui::TextColored(variconColor, "%s", varIcon.c_str());
			ImGui::SameLine();

			const std::string varEntryName=
				StringUtils::stringify(variable->getName(), "##property", std::to_string(propertyId));
			bool isSelected= m_objectSelection.getObjectIdType() == GraphObjectIdType::VARIABLE;
			isSelected= isSelected && (m_objectSelection.getObjectId(0) == variable->getId());
			if (ImGui::Selectable(varEntryName.c_str(), &isSelected))
			{
				clearCanvasSelection();
				if (isSelected)
				{
					m_objectSelection= GraphObjectSelection(GraphObjectIdType::VARIABLE, 1);
					m_objectSelection.setObjectId(0, variable->getId());
				}
				else
				{
					m_objectSelection.clear();
				}
			}
			{
				MkGuiScopedDragDropSource dds(ImGuiDragDropFlags_None);
				if (dds)
				{
					ImGui::SetDragDropPayload(variable->getClassName().c_str(), &variable, sizeof(GraphPropertyPtr));
					ImGui::TextUnformatted(variable->getName().c_str());
				}
			}

			// Dropping a variable onto another row reorders the list. The row's
			// target only opens while that row is hovered, so dragging out to
			// the graph still creates a node instead.
			for (auto propertyFactory : getNodeGraph()->editorGetValidPropertyFactories(m_editorState))
			{
				auto droppedVariable=
					MkGui::receiveTypedDragDropPayload<GraphProperty>(propertyFactory->getGraphPropertyClassName());
				if (droppedVariable && droppedVariable->getId() != propertyId)
				{
					pendingReorderMovedId= droppedVariable->getId();
					pendingReorderTargetId= propertyId;
					break;
				}
			}

			// Context menu
			{
				MkGuiScopedStyle varContextMenuStyle(m_styleManager->getStyle("node_editor_context_menu"));
				MkGuiScopedPopupContextItem varContextMenu;
				if (varContextMenu)
				{
					clearCanvasSelection();
					m_objectSelection= GraphObjectSelection(GraphObjectIdType::VARIABLE, 1);
					m_objectSelection.setObjectId(0, variable->getId());

					if (ImGui::MenuItem(locLabel("nodeEditor.delete"), ICON_FK_TRASH, "DELETE"))
					{
						getNodeGraph()->deletePropertyById(propertyId);
						m_objectSelection.clear();
					}
				}
			}
		}

		if (pendingReorderMovedId != -1)
		{
			getNodeGraph()->reorderPropertyBefore(pendingReorderMovedId, pendingReorderTargetId);
		}
	}

	// Drag and drop creation (variables carry no canvas position)
	handleGraphVariablesDragDrop(m_editorState);

	renderNewGraphVariablesContextMenu(m_editorState);
}

void NodeEditorWindow::renderNewGraphVariablesContextMenu(const NodeEditorState& editorState)
{
	// Don't show context menu if a variable is selected
	if (m_objectSelection.hasSelectionOfType(GraphObjectIdType::VARIABLE))
		return;

	if (ImGui::GetMouseDragDelta(ImGuiMouseButton_Right).x == 0.0f
		&& ImGui::GetMouseDragDelta(ImGuiMouseButton_Right).y == 0.0f && ImGui::IsMouseReleased(ImGuiMouseButton_Right)
		&& ImGui::IsWindowHovered(ImGuiHoveredFlags_ChildWindows))
	{
		ImGui::OpenPopup("editor_context_menu_nodes");
	}

	MkGuiScopedStyle newVarMenuStyle(m_styleManager->getStyle("node_editor_context_menu"));
	MkGuiScopedPopup newVarPopup("editor_context_menu_nodes");
	if (newVarPopup)
	{
		NodeGraphPtr nodeGraph= getNodeGraph();
		if (nodeGraph)
		{
			std::vector<GraphPropertyFactoryPtr> propertyFactories=
				getNodeGraph()->editorGetValidPropertyFactories(editorState);

			for (GraphPropertyFactoryPtr propertyFactory : propertyFactories)
			{
				const std::string propertyTitle= propertyFactory->getDefaultGraphPropertyObject()->editorGetTitle();

				if (ImGui::MenuItem(propertyTitle.c_str()))
				{
					GraphPropertyPtr newVariable= getNodeGraph()->createProperty(propertyFactory);

					clearCanvasSelection();

					m_objectSelection= GraphObjectSelection(GraphObjectIdType::VARIABLE, 1);
					m_objectSelection.setObjectId(0, newVariable->getId());
					break;
				}
			}
		}
	}
}

void NodeEditorWindow::renderAssetsPanel()
{
	NodeGraphPtr nodeGraph= getNodeGraph();

	MkGuiScopedChild assetSubFrame("AssetSubFrame");

	ImGui::SetCursorPos(ImVec2(ImGui::GetCursorPos().x + 6, ImGui::GetCursorPos().y + 1));

	if (nodeGraph)
	{
		auto& factoryMap= nodeGraph->getAssetReferenceFactories();
		for (auto it= factoryMap.begin(); it != factoryMap.end(); it++)
		{
			auto& assetRefFactory= it->second;
			const std::string& assetTypeName= assetRefFactory->getAssetTypeName();
			const std::string addAssetLabel= locFormat("nodeEditor.addAssetFmt", assetTypeName.c_str());
			const std::string buttonName=
				StringUtils::stringify(ICON_FK_PLUS_CIRCLE "  ", addAssetLabel, "##", assetTypeName);

			if (ImGui::SmallButton(buttonName.c_str()))
			{
				const char* picked= tinyfd_openFileDialog(
					assetRefFactory->getFileDialogTitle(), assetRefFactory->getDefaultPath(),
					assetRefFactory->getFilterPatternCount(), assetRefFactory->getFilterPatterns(),
					assetRefFactory->getFilterDescription(), 1);

				if (picked != nullptr && picked[0] != '\0')
				{
					std::stringstream ssPaths(picked);
					std::string path;
					while (std::getline(ssPaths, path, '|'))
					{
						std::string universalPath(path);
						std::replace(universalPath.begin(), universalPath.end(), '\\', '/');

						// Create the asset reference
						AssetReferencePtr assetRef= assetRefFactory->allocateAssetReference();
						if (assetRef)
						{
							// Assign path to the asset
							assetRef->setAssetPath(universalPath);

							// Register the asset reference with the graph
							nodeGraph->getAssetReferencesMutable().push_back(assetRef);
							onAssetReferenceCreated(assetRef);
						}
					}
				}
			}
			ImGui::SameLine();
		}
	}

	ImGui::SetCursorPosY(ImGui::GetCursorPosY() + 18);
	ImGui::Separator();

	// Assets browser
	if (nodeGraph)
	{
		auto& assetRefArray= nodeGraph->getAssetReferences();

		MkGuiScopedChild assetBrowser("AssetBrowser");

		ImGui::Dummy(ImVec2(1, 10));
		for (int assetIndex= 0; assetIndex < assetRefArray.size(); assetIndex++)
		{
			AssetReferencePtr assetRefPtr= assetRefArray[assetIndex];

			ImGui::Dummy(ImVec2(10, 140));
			ImGui::SameLine();
			{
				MkGuiScopedGroup assetGroup;
				std::string idStr= "##asset" + std::to_string(assetIndex);
				ImGui::Button(idStr.c_str(), ImVec2(120, 140));

				{
					MkGuiScopedDragDropSource dds(ImGuiDragDropFlags_None);
					if (dds)
					{
						ImGui::SetDragDropPayload(assetRefPtr->getClassName().c_str(), &assetRefPtr,
												  sizeof(AssetReferencePtr));
						ImGui::TextUnformatted(assetRefPtr->getShortName().c_str());
					}
				}

				// Context menu
				bool itemDeleted= false;
				{
					MkGuiScopedStyle assetContextMenuStyle(m_styleManager->getStyle("node_editor_context_menu"));
					MkGuiScopedPopupContextItem assetContextMenu;
					if (assetContextMenu)
					{
						clearCanvasSelection();

						m_objectSelection= GraphObjectSelection(GraphObjectIdType::ASSET, 1);
						m_objectSelection.setObjectId(0, assetIndex);

						if (ImGui::MenuItem(locLabel("nodeEditor.delete"), ICON_FK_TRASH, "DELETE"))
						{
							deleteSelectedItem();
							itemDeleted= true;
						}
					}
				}

				if (!itemDeleted)
				{
					IMkTexturePtr texture= assetRefPtr->getPreviewTexture();

					ImGui::SetCursorPosX(ImGui::GetCursorPosX() + 10);
					ImGui::SetCursorPosY(ImGui::GetCursorPosY() - 130);

					if (texture && texture->getGlTextureId() != 0)
					{
						ImGui::Image((void*)(intptr_t)texture->getGlTextureId(), ImVec2(100, 100));
					}
					else
					{
						// Type icon stand-in for assets with no preview image
						const ImVec2 tileMin= ImGui::GetCursorScreenPos();
						ImGui::Dummy(ImVec2(100, 100));

						const char* icon= assetRefPtr->editorGetIcon();
						ImFont* font= ImGui::GetFont();
						const float iconFontSize= ImGui::GetFontSize() * 3.f;
						const ImVec2 iconSize= font->CalcTextSizeA(iconFontSize, FLT_MAX, 0.f, icon);
						const ImVec2 iconPos(tileMin.x + (100.f - iconSize.x) * 0.5f,
											 tileMin.y + (100.f - iconSize.y) * 0.5f);
						ImGui::GetWindowDrawList()->AddText(font, iconFontSize, iconPos,
															ImGui::GetColorU32(ImGuiCol_Text), icon);
					}
					ImGui::Dummy(ImVec2(2, 1));
					ImGui::SameLine();

					const std::string& shortName= assetRefPtr->getShortName();
					const std::string clippedName= truncateTextWithEllipsis(shortName, 104.f);
					ImGui::TextUnformatted(clippedName.c_str());
					if (ImGui::IsItemHovered() && clippedName != shortName)
					{
						ImGui::SetTooltip("%s", shortName.c_str());
					}
				}
			}

			ImGui::SameLine();
			if (ImGui::GetContentRegionAvail().x < 130)
			{
				ImGui::NewLine();
				ImGui::NewLine();
			}
		}
		ImGui::NewLine();
		ImGui::Dummy(ImVec2(1, 10));
	}
}

void NodeEditorWindow::renderSelectedObjectPanel()
{
	if (m_objectSelection.getObjectIdType() == GraphObjectIdType::NODE)
	{
		NodePtr node= getNodeGraph()->getNodeById(m_objectSelection.getObjectId(0));

		if (node)
		{
			node->editorRenderPropertySheet(m_editorState);
		}
	}
	else if (m_objectSelection.getObjectIdType() == GraphObjectIdType::ASSET)
	{
		const int assetIndex= m_objectSelection.getObjectId(0);
		const std::vector<AssetReferencePtr>& assetArray= getNodeGraph()->getAssetReferences();

		if (assetIndex >= 0 && assetIndex < (int)assetArray.size())
		{
			assetArray[assetIndex]->editorRenderPropertySheet(m_editorState);
		}
	}
	else if (m_objectSelection.getObjectIdType() == GraphObjectIdType::VARIABLE)
	{
		GraphPropertyPtr property= getNodeGraph()->getPropertyById(m_objectSelection.getObjectId(0));

		if (property)
		{
			renderVariableNameField(property);
			property->editorRenderPropertySheet(m_editorState);
		}
	}
}

void NodeEditorWindow::renderVariableNameField(GraphPropertyPtr property)
{
	// Refill the edit buffer when the selection moves to a different variable,
	// leaving in-progress typing alone otherwise
	if (m_variableNameBufferId != property->getId())
	{
		m_variableNameBufferId= property->getId();
		strncpy(m_variableNameBuffer, property->getName().c_str(), sizeof(m_variableNameBuffer) - 1);
		m_variableNameBuffer[sizeof(m_variableNameBuffer) - 1]= '\0';
	}

	MkGuiStyleConstPtr propertyStyle= m_styleManager->getStyle("node_editor_property_value");
	// The label is drawn as plain text and the field id comes from the fieldName
	// argument, so this takes locText rather than locLabel
	if (MkGui::drawStringProperty(propertyStyle, "variableName", locText("nodeEditor.variableName"),
								  m_variableNameBuffer, sizeof(m_variableNameBuffer)))
	{
		const std::string typedName= m_variableNameBuffer;
		const size_t firstIndex= typedName.find_first_not_of(" \t");
		const size_t lastIndex= typedName.find_last_not_of(" \t");
		const std::string newName= (firstIndex == std::string::npos)
									   ? std::string()
									   : typedName.substr(firstIndex, lastIndex - firstIndex + 1);

		if (!newName.empty())
		{
			property->setName(newName);
			property->notifyPropertyModified();
		}

		// Reflect whatever the property actually kept (an all-space entry is dropped)
		strncpy(m_variableNameBuffer, property->getName().c_str(), sizeof(m_variableNameBuffer) - 1);
		m_variableNameBuffer[sizeof(m_variableNameBuffer) - 1]= '\0';
	}
}

void NodeEditorWindow::deleteSelectedItem()
{
	if (m_objectSelection.getObjectIdType() == GraphObjectIdType::NODE)
	{
		for (int i= 0; i < m_objectSelection.getObjectCount(); i++)
		{
			const t_node_id nodeId= m_objectSelection.getObjectId(i);
			NodePtr node= getNodeGraph()->getNodeById(nodeId);

			if (node && node->editorCanDelete())
			{
				getNodeGraph()->deleteNodeById(nodeId);
			}
		}

		m_objectSelection.clear();
	}
	else if (m_objectSelection.getObjectIdType() == GraphObjectIdType::LINK)
	{
		for (int i= 0; i < m_objectSelection.getObjectCount(); i++)
		{
			const t_node_link_id linkId= m_objectSelection.getObjectId(i);

			getNodeGraph()->deleteLinkById(linkId);
		}

		m_objectSelection.clear();
	}
	else if (m_objectSelection.getObjectIdType() == GraphObjectIdType::VARIABLE)
	{
		for (int i= 0; i < m_objectSelection.getObjectCount(); i++)
		{
			const t_graph_property_id propertyId= m_objectSelection.getObjectId(i);

			getNodeGraph()->deletePropertyById(propertyId);
		}

		m_objectSelection.clear();
	}
	else if (m_objectSelection.getObjectIdType() == GraphObjectIdType::ASSET && m_objectSelection.getObjectCount() > 0)
	{
		const std::vector<AssetReferencePtr>& assetList= getNodeGraph()->getAssetReferences();
		const int assetIndex= m_objectSelection.getObjectId(0);

		if (assetIndex >= 0 && assetIndex < (int)assetList.size())
		{
			getNodeGraph()->deleteAssetReference(assetList[assetIndex]);
		}
		m_objectSelection.clear();
	}
}

NodeGraphFactoryPtr NodeEditorWindow::getNodeGraphFactory() const { return std::make_shared<NodeGraphFactory>(); }

void NodeEditorWindow::newGraph()
{
	// Push this window's GL context before graph resource creation (VAOs, VBOs).
	// Graph creation may be triggered while a different window's context is current
	// (e.g. when bindCompositorComponent is called after createAppWindowInternal pops
	// the editor window's context). VAOs are not shared between GL contexts.
	auto* ownerApp= getOwnerApp();
	auto* windowContext= m_mkWindowContext.get();
	ownerApp->getWindowManager()->pushCurrentWindowContext(windowContext);

	m_editorState.nodeGraph= getNodeGraphFactory()->initialCreateNodeGraph(this);

	ownerApp->getWindowManager()->popCurrentWindowContext(windowContext);

	onNodeGraphCreated();

	if (m_editorState.nodeGraph)
	{
		m_history.reset(m_editorState.nodeGraph->saveToSnapshotString());
		logGraphBaseline();
	}
}

bool NodeEditorWindow::loadGraph(const std::filesystem::path& path)
{
	// Push this window's GL context before graph resource creation (VAOs, VBOs).
	// See comment in newGraph() for details.
	auto* ownerApp= getOwnerApp();
	auto* windowContext= m_mkWindowContext.get();
	ownerApp->getWindowManager()->pushCurrentWindowContext(windowContext);

	m_editorState.nodeGraph= NodeGraphFactory::loadNodeGraph(this, path);

	ownerApp->getWindowManager()->popCurrentWindowContext(windowContext);

	if (m_editorState.nodeGraph)
	{
		m_editorState.nodeGraphPath= path;
		onNodeGraphCreated();
		m_history.reset(m_editorState.nodeGraph->saveToSnapshotString());
		logGraphBaseline();
		return true;
	}
	else
	{
		MIKAN_LOG_ERROR("NodeEditorWindow::load") << "Failed to load node graph: " << path;
	}

	return false;
}

bool NodeEditorWindow::saveGraph(bool bShowFileDialog)
{
	auto resolvedPath= PathUtils::resolveProjectResource(m_editorState.nodeGraphPath);

	// If no path was set (or non resolved) or we explicitly want to show the file dialog,
	// bring up the save path dialog
	if (resolvedPath.empty() || bShowFileDialog)
	{
		std::string defautPath= (PathUtils::getProjectDirectory() / "graphs" / "new_graph.graph").string();
		const char* filterItems[1]= {"*.graph"};
		const char* filterDesc= locText("nodeEditor.graphFilesFilterDescription");

		const char* picked= tinyfd_saveFileDialog(locText("nodeEditor.saveCompositorGraphDialogTitle"),
												  defautPath.c_str(), 1, filterItems, filterDesc);

		if (picked != nullptr && picked[0] != '\0')
		{
			m_editorState.nodeGraphPath= picked;
			resolvedPath= picked;
		}
	}

	if (!resolvedPath.empty() && m_editorState.nodeGraph)
	{
		NodeGraphFactory::saveNodeGraph(resolvedPath, m_editorState.nodeGraph);
		return true;
	}

	return false;
}

void NodeEditorWindow::undo()
{
	// Applied at the top of the next update, outside the ImGui frame
	m_pendingHistorySteps-= 1;
}

void NodeEditorWindow::redo() { m_pendingHistorySteps+= 1; }

bool NodeEditorWindow::stepHistory(int steps)
{
	// Walk the cursor first so a multi-step request rebuilds the graph once
	const bool bIsUndo= steps < 0;
	int appliedSteps= 0;
	const std::string* targetSnapshot= nullptr;
	while (steps != 0)
	{
		const std::string* snapshot= bIsUndo ? m_history.undo() : m_history.redo();
		if (snapshot == nullptr)
		{
			break;
		}

		targetSnapshot= snapshot;
		appliedSteps++;
		steps+= bIsUndo ? 1 : -1;
	}

	if (targetSnapshot == nullptr)
	{
		return false;
	}

	if (!restoreGraphSnapshot(*targetSnapshot))
	{
		m_logWriter.writeEvent("restore_failed");
		return false;
	}

	m_logWriter.writeHistoryStep(bIsUndo ? "undo" : "redo", appliedSteps, m_history.getCursor(),
								 m_editorState.nodeGraph->saveToSnapshotConfig());

	return true;
}

bool NodeEditorWindow::restoreGraphSnapshot(const std::string& snapshot)
{
	m_bApplyingHistory= true;

	// Push this window's GL context before graph resource creation (VAOs, VBOs).
	// See comment in newGraph() for details.
	auto* ownerApp= getOwnerApp();
	auto* windowContext= m_mkWindowContext.get();
	ownerApp->getWindowManager()->pushCurrentWindowContext(windowContext);

	NodeGraphPtr restoredGraph= NodeGraphFactory::loadNodeGraphFromSnapshotString(this, snapshot);

	ownerApp->getWindowManager()->popCurrentWindowContext(windowContext);

	if (!restoredGraph)
	{
		MIKAN_LOG_ERROR("NodeEditorWindow::restoreGraphSnapshot") << "Failed to rebuild graph from snapshot";
		m_bApplyingHistory= false;
		return false;
	}

	// Swap in the restored graph using the same window plumbing a load uses
	onNodeGraphDeleted();
	m_editorState.nodeGraph= restoredGraph;
	m_editorState.startedLinkPinId= -1;
	m_editorState.bLinkHanged= false;
	onNodeGraphCreated();

	// Stale selections may reference objects the snapshot does not contain
	{
		MkGuiScopedContext scopedContext(*m_guiContext.get());
		clearCanvasSelection();
	}
	m_objectSelection.clear();

	// Let subclasses rebind the restored graph to its owning component
	onGraphRestored();

	m_bCheckpointPending= false;
	m_bApplyingHistory= false;

	return true;
}

void NodeEditorWindow::updateHistoryCapture()
{
	if (m_bApplyingHistory)
	{
		return;
	}

	// Edits with no graph delegate (node property sheets, node drags) surface
	// as a widget going inactive or a mouse release; commit dedup drops false triggers
	const bool bAnyItemActive= ImGui::IsAnyItemActive();
	if ((m_bAnyItemActiveLastFrame && !bAnyItemActive) || ImGui::IsMouseReleased(ImGuiMouseButton_Left))
	{
		m_bCheckpointPending= true;
	}
	m_bAnyItemActiveLastFrame= bAnyItemActive;

	// Commit once the interaction settles, coalescing a burst (a delete
	// cascade, a whole drag) into a single undo step
	if (m_bCheckpointPending && !bAnyItemActive && !ImGui::IsMouseDown(ImGuiMouseButton_Left))
	{
		NodeGraphPtr nodeGraph= getNodeGraph();
		if (nodeGraph)
		{
			const configuru::Config snapshotConfig= nodeGraph->saveToSnapshotConfig();
			if (m_history.commit(configuru::dump_string(snapshotConfig, configuru::JSON)))
			{
				m_logWriter.writeSnapshotCommit(m_nextLogSequenceNumber++, snapshotConfig);
			}
		}
		m_bCheckpointPending= false;
	}
}

void NodeEditorWindow::clearCanvasSelection()
{
	if (m_canvasContext == nullptr)
	{
		return;
	}

	ax::NodeEditor::EditorContext* prevContext= ed::GetCurrentEditor();
	ed::SetCurrentEditor(m_canvasContext);
	ed::ClearSelection();
	ed::SetCurrentEditor(prevContext);
}

void NodeEditorWindow::logGraphBaseline()
{
	NodeGraphPtr nodeGraph= m_editorState.nodeGraph;
	if (!nodeGraph)
	{
		return;
	}

	// One log file per window session, opened when the first graph arrives.
	// Skipped when no project is loaded (the log lives in the project folder).
	if (!m_logWriter.isOpen())
	{
		ProjectManagerPtr projectManager= getProjectManager();
		ProjectConfigPtr projectConfig= projectManager ? projectManager->getProjectConfig() : nullptr;
		if (!projectConfig)
		{
			return;
		}

		std::string windowClassName= typeid(*this).name();
		if (windowClassName.rfind("class ", 0) == 0)
		{
			windowClassName= windowClassName.substr(6);
		}

		if (!m_logWriter.open(projectConfig->getLoadedConfigPath(), windowClassName))
		{
			return;
		}
	}

	m_logWriter.writeBaseline(m_editorState.nodeGraphPath, nodeGraph->getClassName(),
							  nodeGraph->saveToSnapshotConfig());
}

void NodeEditorWindow::enqueueAutomationTask(std::function<void()>&& task)
{
	m_automationTasks.push_back(std::move(task));
}

void NodeEditorWindow::flushAutomationTasks()
{
	while (!m_automationTasks.empty())
	{
		std::function<void()> task= std::move(m_automationTasks.front());
		m_automationTasks.erase(m_automationTasks.begin());
		task();
	}
}

bool NodeEditorWindow::wantsDestroy() const { return m_bCloseRequested || EditorWindow::wantsDestroy(); }

bool NodeEditorWindow::automationCreateNode(const std::string& nodeClassName, const glm::vec2& gridPos,
											t_node_id& outNodeId, std::string& outError)
{
	NodeGraphPtr nodeGraph= getNodeGraph();
	if (!nodeGraph)
	{
		outError= "no graph loaded";
		return false;
	}

	NodeFactoryPtr nodeFactory= nodeGraph->getNodeFactory(nodeClassName);
	if (!nodeFactory)
	{
		outError= "unknown node class '" + nodeClassName + "'";
		return false;
	}

	// Node creation touches GL resources and, via onNodeCreated, canvas editor state
	auto* ownerApp= getOwnerApp();
	auto* windowContext= m_mkWindowContext.get();
	ownerApp->getWindowManager()->pushCurrentWindowContext(windowContext);
	NodePtr newNode;
	{
		MkGuiScopedContext scopedContext(*m_guiContext.get());

		m_editorState.hangPosGridSpace= ImVec2(gridPos.x, gridPos.y);
		newNode= nodeGraph->createNode(nodeFactory, m_editorState);
	}
	ownerApp->getWindowManager()->popCurrentWindowContext(windowContext);

	if (!newNode)
	{
		outError= "node creation failed";
		return false;
	}

	outNodeId= newNode->getId();
	return true;
}

bool NodeEditorWindow::automationDeleteNode(t_node_id nodeId, std::string& outError)
{
	NodeGraphPtr nodeGraph= getNodeGraph();
	if (!nodeGraph)
	{
		outError= "no graph loaded";
		return false;
	}

	NodePtr node= nodeGraph->getNodeById(nodeId);
	if (!node)
	{
		outError= "no node with id " + std::to_string(nodeId);
		return false;
	}

	if (!node->editorCanDelete())
	{
		outError= "node " + std::to_string(nodeId) + " is not deletable";
		return false;
	}

	auto* ownerApp= getOwnerApp();
	auto* windowContext= m_mkWindowContext.get();
	ownerApp->getWindowManager()->pushCurrentWindowContext(windowContext);
	{
		MkGuiScopedContext scopedContext(*m_guiContext.get());

		nodeGraph->deleteNodeById(nodeId);
	}
	ownerApp->getWindowManager()->popCurrentWindowContext(windowContext);

	return true;
}

bool NodeEditorWindow::automationCreateLink(t_node_pin_id startPinId, t_node_pin_id endPinId, t_node_link_id& outLinkId,
											std::string& outError)
{
	NodeGraphPtr nodeGraph= getNodeGraph();
	if (!nodeGraph)
	{
		outError= "no graph loaded";
		return false;
	}

	NodePinPtr startPin= nodeGraph->getPinById(startPinId);
	if (!startPin)
	{
		outError= "no pin with id " + std::to_string(startPinId);
		return false;
	}

	NodePinPtr endPin= nodeGraph->getPinById(endPinId);
	if (!endPin)
	{
		outError= "no pin with id " + std::to_string(endPinId);
		return false;
	}

	if (!startPin->canPinsBeConnected(endPin))
	{
		outError= "pins " + std::to_string(startPinId) + " and " + std::to_string(endPinId) + " cannot connect";
		return false;
	}

	auto* ownerApp= getOwnerApp();
	auto* windowContext= m_mkWindowContext.get();
	ownerApp->getWindowManager()->pushCurrentWindowContext(windowContext);
	NodeLinkPtr link;
	{
		MkGuiScopedContext scopedContext(*m_guiContext.get());

		link= nodeGraph->createLink(startPinId, endPinId);
	}
	ownerApp->getWindowManager()->popCurrentWindowContext(windowContext);

	if (!link)
	{
		outError= "link creation failed";
		return false;
	}

	outLinkId= link->getId();
	return true;
}

bool NodeEditorWindow::automationDeleteLink(t_node_link_id linkId, std::string& outError)
{
	NodeGraphPtr nodeGraph= getNodeGraph();
	if (!nodeGraph)
	{
		outError= "no graph loaded";
		return false;
	}

	if (!nodeGraph->getLinkById(linkId))
	{
		outError= "no link with id " + std::to_string(linkId);
		return false;
	}

	auto* ownerApp= getOwnerApp();
	auto* windowContext= m_mkWindowContext.get();
	ownerApp->getWindowManager()->pushCurrentWindowContext(windowContext);
	{
		MkGuiScopedContext scopedContext(*m_guiContext.get());

		nodeGraph->deleteLinkById(linkId);
	}
	ownerApp->getWindowManager()->popCurrentWindowContext(windowContext);

	return true;
}

void NodeEditorWindow::onNodeGraphCreated()
{
	MkGuiScopedContext scopedContext(*m_guiContext.get());
	NodeGraphPtr graph= getNodeGraph();

	graph->OnNodeCreated+= MakeDelegate(this, &NodeEditorWindow::onNodeCreated);
	graph->OnNodeDeleted+= MakeDelegate(this, &NodeEditorWindow::onNodeDeleted);
	graph->OnLinkCreated+= MakeDelegate(this, &NodeEditorWindow::onLinkCreated);
	graph->OnLinkDeleted+= MakeDelegate(this, &NodeEditorWindow::onLinkDeleted);
	graph->OnPinCreated+= MakeDelegate(this, &NodeEditorWindow::onPinCreated);
	graph->OnPinDeleted+= MakeDelegate(this, &NodeEditorWindow::onPinDeleted);
	graph->OnPropertyCreated+= MakeDelegate(this, &NodeEditorWindow::onGraphPropertyCreated);
	graph->OnPropertyModifed+= MakeDelegate(this, &NodeEditorWindow::onGraphPropertyModified);
	graph->OnPropertyDeleted+= MakeDelegate(this, &NodeEditorWindow::onGraphPropertyDeleted);
	graph->OnAssetReferenceDeleted+= MakeDelegate(this, &NodeEditorWindow::onAssetReferenceDeleted);

	// Register the node positions with the canvas (called outside the canvas
	// frame scope, so bracket the editor context explicitly)
	if (m_canvasContext != nullptr)
	{
		ax::NodeEditor::EditorContext* prevContext= ed::GetCurrentEditor();
		ed::SetCurrentEditor(m_canvasContext);
		for (auto iter= graph->getNodesMap().begin(); iter != graph->getNodesMap().end(); iter++)
		{
			const t_node_id nodeId= iter->first;
			NodePtr node= iter->second;

			const glm::vec2& nodePos= node->getNodePos();
			ed::SetNodePosition(MkCanvas::toCanvasId(nodeId), ImVec2(nodePos.x, nodePos.y));
		}
		ed::SetCurrentEditor(prevContext);
	}
}

void NodeEditorWindow::onNodeGraphDeleted()
{
	NodeGraphPtr graph= getNodeGraph();

	if (graph)
	{
		graph->OnNodeCreated-= MakeDelegate(this, &NodeEditorWindow::onNodeCreated);
		graph->OnNodeDeleted-= MakeDelegate(this, &NodeEditorWindow::onNodeDeleted);
		graph->OnLinkCreated-= MakeDelegate(this, &NodeEditorWindow::onLinkCreated);
		graph->OnLinkDeleted-= MakeDelegate(this, &NodeEditorWindow::onLinkDeleted);
		graph->OnPinCreated-= MakeDelegate(this, &NodeEditorWindow::onPinCreated);
		graph->OnPinDeleted-= MakeDelegate(this, &NodeEditorWindow::onPinDeleted);
		graph->OnPropertyCreated-= MakeDelegate(this, &NodeEditorWindow::onGraphPropertyCreated);
		graph->OnPropertyModifed-= MakeDelegate(this, &NodeEditorWindow::onGraphPropertyModified);
		graph->OnPropertyDeleted-= MakeDelegate(this, &NodeEditorWindow::onGraphPropertyDeleted);
		graph->OnAssetReferenceDeleted-= MakeDelegate(this, &NodeEditorWindow::onAssetReferenceDeleted);
	}
}

void NodeEditorWindow::onNodeCreated(t_node_id id)
{
	// Place the new node at the captured cursor position and select it.
	// Every creation path (context menu, drag drop, automation) fires this
	// outside the canvas frame scope, so bracket the editor context.
	const ImVec2& hangPosGridSpace= m_editorState.hangPosGridSpace;
	NodePtr node= getNodeGraph()->getNodeById(id);
	if (node)
	{
		node->setNodePos(glm::vec2(hangPosGridSpace.x, hangPosGridSpace.y));
	}

	if (m_canvasContext != nullptr)
	{
		ax::NodeEditor::EditorContext* prevContext= ed::GetCurrentEditor();
		ed::SetCurrentEditor(m_canvasContext);
		ed::SetNodePosition(MkCanvas::toCanvasId(id), hangPosGridSpace);
		ed::ClearSelection();
		ed::SelectNode(MkCanvas::toCanvasId(id));
		ed::SetCurrentEditor(prevContext);
	}

	// Make the newly created node selected
	m_objectSelection= GraphObjectSelection(GraphObjectIdType::NODE, 1);
	m_objectSelection.setObjectId(0, id);

	markHistoryCheckpoint();
}

void NodeEditorWindow::onNodeDeleted(t_node_id id)
{
	// The canvas selection resyncs against live graph ids each frame, so only
	// the window-level selection needs fixing here
	if (m_objectSelection.getObjectIdType() == GraphObjectIdType::NODE)
	{
		m_objectSelection.removeObjectId(id);
	}

	markHistoryCheckpoint();
}

void NodeEditorWindow::onLinkCreated(t_node_link_id id) { markHistoryCheckpoint(); }

void NodeEditorWindow::onLinkDeleted(t_node_link_id id)
{
	if (m_objectSelection.getObjectIdType() == GraphObjectIdType::LINK)
	{
		m_objectSelection.removeObjectId(id);
	}

	markHistoryCheckpoint();
}

void NodeEditorWindow::onPinCreated(t_node_pin_id id) { markHistoryCheckpoint(); }

void NodeEditorWindow::onPinDeleted(t_node_pin_id id) { markHistoryCheckpoint(); }

void NodeEditorWindow::onGraphPropertyCreated(t_graph_property_id id) { markHistoryCheckpoint(); }

void NodeEditorWindow::onGraphPropertyModified(t_graph_property_id id) { markHistoryCheckpoint(); }

void NodeEditorWindow::onGraphPropertyDeleted(t_graph_property_id id) { markHistoryCheckpoint(); }

void NodeEditorWindow::onAssetReferenceCreated(AssetReferencePtr assetRef) { markHistoryCheckpoint(); }

void NodeEditorWindow::onAssetReferenceDeleted(AssetReferencePtr assetRef) { markHistoryCheckpoint(); }

void NodeEditorWindow::shutdown()
{
	// Run parked automation work so its deferred replies still send
	flushAutomationTasks();

	onNodeGraphDeleted();
	m_editorState.nodeGraph= nullptr;
	m_editorState.nodeGraphPath.clear();
	m_logWriter.close();

	if (m_canvasContext != nullptr)
	{
		MkGuiScopedContext scopedContext(*m_guiContext.get());

		MkCanvas::destroyEditorContext(m_canvasContext);
		m_canvasContext= nullptr;
	}

	shutdownTextureCache();
	shutdownModelResourceManager();
	shutdownStyleManager();
	shutdownGuiContext();
	shutdownWindow();
}

// -- IMkWindowEventListener
bool NodeEditorWindow::onWindowEvent(const MkWindowEvent& event) { return m_guiContext->onWindowEvent(event); }
