//-- includes -----
#include "NodeEditorWindow.h"
#include "Logger.h"
#include "MkGuiContext.h"
#include "MkGuiScopedStyle.h"
#include "MkGuiStyleManager.h"
#include "MkGuiScopedUpdate.h"
#include "MkGuiScopedContext.h"
#include "MkGuiScopedChild.h"
#include "MkGuiScopedWindow.h"
#include "MkGuiScopedGroup.h"
#include "MkGuiScopedPopup.h"
#include "MkGuiScopedTabBar.h"
#include "MkGuiScopedTabItem.h"
#include "MkGuiScopedDragDropSource.h"
#include "MkGuiScopedDragDropTarget.h"
#include "MkNodesScopedNodeEditor.h"

#include "App.h"
#include "AssetReference.h"
#include "IMkGraphicsContext.h"
#include "MikanModelResourceManager.h"
#include "IMkViewport.h"
#include "MkStateStack.h"
#include "IMkState.h"
#include "MkStateModifiers.h"
#include "MkWindowEvent.h"
#include "IMkTexture.h"
#include "Graphs/NodeGraph.h"
#include "Graphs/NodeEvaluator.h"
#include "Nodes/Node.h"
#include "LocText.h"
#include "MkGuiDrawUtils.h"
#include "PathUtils.h"
#include "StringUtils.h"
#include "TextStyle.h"

#include "Pins/NodeLink.h"
#include "Pins/NodePin.h"

#include "imgui.h"
#include "imnodes.h"

// Autogenerated header containing Unicode Icon IDs from "forkawesome-webfont.ttf"
#include "IconsForkAwesome.h"

#include "tinyfiledialogs.h" // Cross-platform file dialogs library

#include <easy/profiler.h>

#include "glm/ext/vector_float4.hpp"

// Drag-Drop Payload Types
#define DRAG_DROP_TYPE_VARIABLE "Variable"
#define DRAG_DROP_TYPE_ASSET_REF "Asset"

//-- public methods -----
NodeEditorWindow::NodeEditorWindow(App* ownerApp)
	: EditorWindow(ownerApp)
{
	shareGraphicsContextWithMainWindow();
}

NodeEditorWindow::~NodeEditorWindow() {}

// -- IEditorWindow ----
bool NodeEditorWindow::startup()
{
	EASY_FUNCTION();

	bool success= true;

	MIKAN_LOG_INFO("NodeEditorWindow::init()") << "Initializing NodeEditorWindow";

	static const int k_node_window_pixel_width= 1080;
	static const int k_node_window_pixel_height= 720;

	if (success && !startupWindow(locText("windows.nodeEditor"), k_node_window_pixel_width, k_node_window_pixel_height))
	{
		success= false;
	}

	if (success && !startupGuiContext("node_editor"))
	{
		success= false;
	}

	if (success && !startupStyleManager())
	{
		success= false;
	}

	if (success)
	{
		m_editorState.styleManager= m_styleManager.get();
	}

	if (success && !startupTextureCache())
	{
		success= false;
	}

	if (success && !startupModelResourceManager())
	{
		success= false;
	}

	return success;
}

void NodeEditorWindow::update(float deltaSeconds)
{
	EASY_FUNCTION();

	// Run parked automation work and scheduled history steps outside the
	// ImGui frame, where graph rebuilds and context pushes are safe
	flushAutomationTasks();
	if (m_pendingHistorySteps != 0)
	{
		const int steps= m_pendingHistorySteps;
		m_pendingHistorySteps= 0;
		stepHistory(steps);
	}

	// Push the ImGui Update scope
	MkGuiScopedUpdate scopedCtx(*m_guiContext);

	// Process most recent SDL events (keyboard, mouse, etc)
	m_mkWindowContext->handleEvents(this);

	// Process UI input and build ImGui draw lists
	updateUI();

	// On Pop: Finalize draw lists and clear ImGui context
}

void NodeEditorWindow::render()
{
	EASY_FUNCTION();

	// Clear the window
	m_graphicsContext->renderBegin();

	{
		// Create a scoped UI rendering settings
		MkScopedState scopedState= m_graphicsContext->getMkStateStack().createScopedState("appStage renderUI");
		IMkState* glState= scopedState.getStackState();

		mkStateSetViewport(glState, 0, 0, (int)m_mkWindowContext->getWidth(), (int)m_mkWindowContext->getHeight());

		// Submit the MkGui draw calls
		m_guiContext->submitDrawData();
	}

	// Finalize rendering
	m_graphicsContext->renderEnd();

	// Present the rendered frame
	m_mkWindowContext->present();
}

void NodeEditorWindow::updateUI()
{
	MkGuiScopedStyle baseStyle(m_styleManager->getStyle("node_editor_base"));

	ImGui::SetNextWindowSize(ImVec2(getWidth(), getHeight()), ImGuiCond_Once);
	MkGuiScopedWindow nodeEditorWindow(locWindowTitle("windows.nodeEditor"), nullptr,
									   ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoBringToFrontOnFocus
										   | ImGuiWindowFlags_NoMove);

	// Toolbar
	renderToolbar();

	// Left Panel
	renderGraphVariablesPanel();

	ImGui::SameLine();
	{
		MkGuiScopedChild mainPanel("Main Panel",
								   ImVec2(ImGui::GetContentRegionAvail().x - 250, ImGui::GetContentRegionAvail().y));

		// Main Frame
		renderMainFrame();

		// Bottom Panel
		renderAssetsPanel();
	}

	// Right Panel
	renderSelectedObjectPanel();

	// Undo/redo chords (Ctrl+Z / Ctrl+Shift+Z); text fields keep ImGui's own undo
	if (ImGui::IsKeyPressed(ImGuiKey_Z, false) && ImGui::GetIO().KeyCtrl && !ImGui::IsAnyItemActive())
	{
		if (ImGui::GetIO().KeyShift)
		{
			redo();
		}
		else
		{
			undo();
		}
	}

	updateHistoryCapture();
}

void NodeEditorWindow::renderMainFrame()
{
	NodeGraphPtr nodeGraph= getNodeGraph();

	{
		MkGuiScopedChild mainChild("Main",
								   ImVec2(ImGui::GetContentRegionAvail().x, ImGui::GetContentRegionAvail().y - 226));
		{
			MkNodesScopedNodeEditor nodeEditor;

			if (nodeGraph)
			{
				nodeGraph->editorRender(m_editorState);
			}
		}
	}

	// Draw error messages on top of related nodes
	renderNodeEvalErrors();

	// Node selection
	if (ImNodes::NumSelectedNodes() > 0)
	{
		GraphObjectSelection selection(GraphObjectIdType::NODE, ImNodes::NumSelectedNodes());

		ImNodes::GetSelectedNodes(selection.getRawObjectArray());
		m_objectSelection= selection;
	}

	// Start link
	if (ImNodes::IsLinkStarted(&m_editorState.startedLinkPinId))
	{
		NodePinPtr pinPtr= getNodeGraph()->getPinById(m_editorState.startedLinkPinId);
		if (pinPtr)
		{
			ImNodes::GetStyle().Colors[ImNodesCol_Link]= pinPtr->editorGetLinkStyleColor();
		}
	}

	// Drop link
	if (ImNodes::IsLinkDropped())
	{
		ImGui::OpenPopup("editor_context_menu_nodes");
		m_editorState.bLinkHanged= true;
		m_editorState.hangPosGridSpace= MkGui::mousePosToGridSpace();
	}

	// Link creation
	int startPinId, endPinId;
	if (ImNodes::IsLinkCreated(&startPinId, &endPinId))
	{
		m_editorState.startedLinkPinId= -1;
		getNodeGraph()->createLink(startPinId, endPinId);
	}

	// Context menu
	renderMainFrameContextMenu(m_editorState);

	// Drag and drop creation
	{
		NodeEditorState editorStateCopy= m_editorState;
		editorStateCopy.hangPosGridSpace= MkGui::mousePosToGridSpace();

		handleMainFrameDragDrop(editorStateCopy);
	}

	// Delete key event (and not focused on a text input)
	if (ImGui::IsKeyPressed(ImGuiKey_Delete, false) && !ImGui::IsAnyItemActive())
	{
		deleteSelectedItem();
	}
}

void NodeEditorWindow::renderNodeEvalErrors()
{
	if (m_editorState.nodeGraph && m_lastNodeEvalErrors.size() > 0)
	{
		size_t errorIter= 0;
		while (errorIter < m_lastNodeEvalErrors.size())
		{
			const NodeEvaluationError* currentError= &m_lastNodeEvalErrors[errorIter];
			const std::string evalWindowId=
				StringUtils::stringify(locText("nodeEditor.evalErrorWindowTitle"), "##Node", currentError->errorNodeId);

			static const float k_errorWindowOffset= 50.f;
			ImVec2 errorPos= currentError->errorNodeId != -1 ? ImNodes::GetNodeScreenSpacePos(currentError->errorNodeId)
															 : ImVec2(0, 0);
			errorPos.y-= k_errorWindowOffset;

			ImGui::SetNextWindowPos(errorPos);
			MkGuiScopedWindow evalWindow(evalWindowId.c_str(), nullptr,
										 ImGuiWindowFlags_NoResize | ImGuiWindowFlags_AlwaysAutoResize
											 | ImGuiWindowFlags_NoNav);
			{
				MkGuiScopedGroup errorGroup;
				MkGuiScopedStyle errorTextStyle(m_styleManager->getStyle("node_editor_error_text"));
				while (errorIter < m_lastNodeEvalErrors.size())
				{
					// Add a bullet point for each error on the same node
					ImGui::BulletText("%s", currentError->errorMessage.c_str());

					// Advance to the next error message on this node
					errorIter++;

					// If the next error is on a different node, move on to the next error window
					if (errorIter < m_lastNodeEvalErrors.size())
					{
						const NodeEvaluationError* nextError= &m_lastNodeEvalErrors[errorIter];

						if (nextError->errorNodeId == currentError->errorNodeId)
						{
							currentError= nextError;
						}
						else
						{
							break;
						}
					}
				}
			}
		}
	}
}

void NodeEditorWindow::renderMainFrameContextMenu(const NodeEditorState& editorState)
{
	if (ImGui::GetMouseDragDelta(ImGuiMouseButton_Right).x == 0.0f
		&& ImGui::GetMouseDragDelta(ImGuiMouseButton_Right).y == 0.0f && ImGui::IsMouseReleased(ImGuiMouseButton_Right)
		&& ImGui::IsWindowHovered(ImGuiHoveredFlags_ChildWindows))
	{
		int id= -1;
		if (ImNodes::IsNodeHovered(&id))
		{
			ImNodes::ClearNodeSelection();
			ImNodes::ClearLinkSelection();
			ImNodes::SelectNode(id);
			m_objectSelection= GraphObjectSelection(GraphObjectIdType::NODE, 1);
			m_objectSelection.setObjectId(0, id);
			ImGui::OpenPopup("editor_context_menu_node");
		}
		else if (ImNodes::IsLinkHovered(&id))
		{
			ImNodes::ClearNodeSelection();
			ImNodes::ClearLinkSelection();
			ImNodes::SelectLink(id);
			m_objectSelection= GraphObjectSelection(GraphObjectIdType::LINK, 1);
			m_objectSelection.setObjectId(0, id);
			ImGui::OpenPopup("editor_context_menu_link");
		}
		else
		{
			ImGui::OpenPopup("editor_context_menu_nodes");
			m_editorState.hangPosGridSpace= MkGui::mousePosToGridSpace();
		}
	}

	MkGuiScopedStyle contextMenuStyle(m_styleManager->getStyle("node_editor_context_menu"));
	{
		MkGuiScopedPopup nodePopup("editor_context_menu_node");
		if (nodePopup)
		{
			NodePtr node;
			if (m_objectSelection.getObjectIdType() == GraphObjectIdType::NODE)
			{
				node= getNodeGraph()->getNodeById(m_objectSelection.getObjectId(0));
			}

			if (node && node->editorCanDelete())
			{
				if (ImGui::MenuItem(locLabel("nodeEditor.delete"), ICON_FK_TRASH, "DELETE"))
				{
					getNodeGraph()->deleteNodeById(m_objectSelection.getObjectId(0));
				}
			}
			else
			{
				ImGui::CloseCurrentPopup();
			}
		}
		else
		{
			MkGuiScopedPopup linkPopup("editor_context_menu_link");
			if (linkPopup)
			{
				if (m_objectSelection.getObjectIdType() == GraphObjectIdType::LINK
					&& ImGui::MenuItem(locLabel("nodeEditor.delete"), ICON_FK_TRASH, "DELETE"))
				{
					getNodeGraph()->deleteLinkById(m_objectSelection.getObjectId(0));
				}
			}
			else
			{
				MkGuiScopedPopup nodesPopup("editor_context_menu_nodes");
				if (nodesPopup)
				{
					NodeGraphPtr nodeGraph= getNodeGraph();
					if (nodeGraph)
					{
						std::vector<NodeFactoryPtr> nodeFactories=
							getNodeGraph()->editorGetValidNodeFactories(editorState);
						for (NodeFactoryPtr nodeFactory : nodeFactories)
						{
							const std::string nodeTitle= nodeFactory->getNodeDefaultObject()->editorGetTitle();

							if (ImGui::MenuItem(nodeTitle.c_str()))
							{
								getNodeGraph()->createNode(nodeFactory, editorState);
								break;
							}
						}
					}
				}
				else if (m_editorState.bLinkHanged)
				{
					m_editorState.bLinkHanged= false;
					m_editorState.startedLinkPinId= -1;
				}
			}
		}
	}
}

void NodeEditorWindow::renderToolbar()
{
	MkGuiScopedStyle toolbarStyle(m_styleManager->getStyle("node_editor_toolbar"));

	MkGuiScopedChild toolbarChild("Toolbar", ImVec2(ImGui::GetContentRegionAvail().x, 40));

	ImGui::SetCursorPosY((ImGui::GetWindowHeight() - 30) * 0.5f);

	const std::string saveButtonLabel= std::string(ICON_FK_FLOPPY_O "   ") + locLabel("nodeEditor.save");
	if (ImGui::Button(saveButtonLabel.c_str(), ImVec2(0, 30)))
	{
		saveGraph(false);
	}

	// Editor Control
	{
		MkGuiScopedStyle controlPanelStyle(m_styleManager->getStyle("node_editor_control_panel"));

		ImGui::SameLine();
		MkGuiScopedChild editorControlChild("EditorControl", ImVec2(70, 30), true, ImGuiWindowFlags_NoScrollbar);
		ImGui::SetCursorPosY((ImGui::GetWindowHeight() - ImGui::GetTextLineHeight()) * 0.5f);

		ImGui::SameLine();
		{
			MkGuiScopedStyle undoStyle(m_styleManager->getStyle("node_editor_undo_button"));
			if (ImGui::SmallButton(ICON_FK_UNDO))
			{
				undo();
			}

			ImGui::SameLine();
			if (ImGui::SmallButton(ICON_FK_REPEAT))
			{
				redo();
			}
		}
	}
}

void NodeEditorWindow::renderGraphVariablesPanel()
{
	MkGuiScopedChild leftPanel("Left Panel", ImVec2(200, ImGui::GetContentRegionAvail().y));

	// Title bar
	ImGui::SetNextItemOpen(true, ImGuiCond_Once);
	bool isNodeOpened;
	{
		MkGuiScopedStyle headerStyle(m_styleManager->getStyle("node_editor_panel_header"));
		isNodeOpened= ImGui::CollapsingHeader(locLabel("nodeEditor.variables"), ImGuiTreeNodeFlags_SpanAvailWidth);
	}

	if (isNodeOpened)
	{
		MkGuiScopedStyle selectionStyle(m_styleManager->getStyle("node_editor_variable_list"));

		auto propertyMap= getNodeGraph()->getPropertyMap();
		for (auto it= propertyMap.begin(); it != propertyMap.end(); it++)
		{
			t_graph_property_id propertyId= it->first;
			GraphPropertyPtr variable= it->second;

			// Variable
			const std::string varIcon= variable->editorGetIcon();
			const ImVec4& variconColor= variable->editorGetIconColor();
			ImGui::TextColored(variconColor, "%s", varIcon.c_str());
			ImGui::SameLine();

			const std::string varEntryName=
				StringUtils::stringify(variable->getName(), "##property", std::to_string(propertyId));
			bool isSelected= m_objectSelection.getObjectIdType() == GraphObjectIdType::VARIABLE;
			isSelected= isSelected && (m_objectSelection.getObjectId(0) == variable->getId());
			if (ImGui::Selectable(varEntryName.c_str(), &isSelected))
			{
				ImNodes::ClearLinkSelection();
				ImNodes::ClearNodeSelection();
				if (isSelected)
				{
					m_objectSelection= GraphObjectSelection(GraphObjectIdType::VARIABLE, 1);
					m_objectSelection.setObjectId(0, variable->getId());
				}
				else
				{
					m_objectSelection.clear();
				}
			}
			{
				MkGuiScopedDragDropSource dds(ImGuiDragDropFlags_None);
				if (dds)
				{
					ImGui::SetDragDropPayload(variable->getClassName().c_str(), &variable, sizeof(GraphPropertyPtr));
					ImGui::TextUnformatted(variable->getName().c_str());
				}
			}

			// Context menu
			{
				MkGuiScopedStyle varContextMenuStyle(m_styleManager->getStyle("node_editor_context_menu"));
				MkGuiScopedPopupContextItem varContextMenu;
				if (varContextMenu)
				{
					ImNodes::ClearLinkSelection();
					ImNodes::ClearNodeSelection();
					m_objectSelection= GraphObjectSelection(GraphObjectIdType::VARIABLE, 1);
					m_objectSelection.setObjectId(0, variable->getId());

					if (ImGui::MenuItem(locLabel("nodeEditor.delete"), ICON_FK_TRASH, "DELETE"))
					{
						getNodeGraph()->deletePropertyById(propertyId);
						m_objectSelection.clear();
					}
				}
			}
		}
	}

	// Drag and drop creation
	{
		NodeEditorState editorStateCopy= m_editorState;
		editorStateCopy.hangPosGridSpace= MkGui::mousePosToGridSpace();

		handleGraphVariablesDragDrop(editorStateCopy);
	}

	renderNewGraphVariablesContextMenu(m_editorState);
}

void NodeEditorWindow::renderNewGraphVariablesContextMenu(const NodeEditorState& editorState)
{
	// Don't show context menu if a variable is selected
	if (m_objectSelection.hasSelectionOfType(GraphObjectIdType::VARIABLE))
		return;

	if (ImGui::GetMouseDragDelta(ImGuiMouseButton_Right).x == 0.0f
		&& ImGui::GetMouseDragDelta(ImGuiMouseButton_Right).y == 0.0f && ImGui::IsMouseReleased(ImGuiMouseButton_Right)
		&& ImGui::IsWindowHovered(ImGuiHoveredFlags_ChildWindows))
	{
		ImGui::OpenPopup("editor_context_menu_nodes");
	}

	MkGuiScopedStyle newVarMenuStyle(m_styleManager->getStyle("node_editor_context_menu"));
	MkGuiScopedPopup newVarPopup("editor_context_menu_nodes");
	if (newVarPopup)
	{
		NodeGraphPtr nodeGraph= getNodeGraph();
		if (nodeGraph)
		{
			std::vector<GraphPropertyFactoryPtr> propertyFactories=
				getNodeGraph()->editorGetValidPropertyFactories(editorState);

			for (GraphPropertyFactoryPtr propertyFactory : propertyFactories)
			{
				const std::string propertyTitle= propertyFactory->getDefaultGraphPropertyObject()->editorGetTitle();

				if (ImGui::MenuItem(propertyTitle.c_str()))
				{
					GraphPropertyPtr newVariable= getNodeGraph()->createProperty(propertyFactory);

					ImNodes::ClearLinkSelection();
					ImNodes::ClearNodeSelection();

					m_objectSelection= GraphObjectSelection(GraphObjectIdType::VARIABLE, 1);
					m_objectSelection.setObjectId(0, newVariable->getId());
					break;
				}
			}
		}
	}
}

void NodeEditorWindow::renderAssetsPanel()
{
	NodeGraphPtr nodeGraph= getNodeGraph();

	MkGuiScopedChild assetsPanel("Assets Panel", ImVec2(ImGui::GetContentRegionAvail().x, 216));
	{
		MkGuiScopedTabBar assetTabBar("AssetsTabBar");
		if (assetTabBar)
		{
			MkGuiScopedStyle assetTabStyle(m_styleManager->getStyle("node_editor_asset_tab"));
			MkGuiScopedTabItem assetTabItem(locLabel("nodeEditor.assetsTab"));
			if (assetTabItem)
			{
				MkGuiScopedChild assetSubFrame("AssetSubFrame");

				ImGui::SetCursorPos(ImVec2(ImGui::GetCursorPos().x + 6, ImGui::GetCursorPos().y + 1));

				if (nodeGraph)
				{
					auto& factoryMap= nodeGraph->getAssetReferenceFactories();
					for (auto it= factoryMap.begin(); it != factoryMap.end(); it++)
					{
						auto& assetRefFactory= it->second;
						const std::string& assetTypeName= assetRefFactory->getAssetTypeName();
						const std::string addAssetLabel= locFormat("nodeEditor.addAssetFmt", assetTypeName.c_str());
						const std::string buttonName=
							StringUtils::stringify(ICON_FK_PLUS_CIRCLE "  ", addAssetLabel, "##", assetTypeName);

						if (ImGui::SmallButton(buttonName.c_str()))
						{
							const char* picked= tinyfd_openFileDialog(
								assetRefFactory->getFileDialogTitle(), assetRefFactory->getDefaultPath(),
								assetRefFactory->getFilterPatternCount(), assetRefFactory->getFilterPatterns(),
								assetRefFactory->getFilterDescription(), 1);

							if (picked != nullptr && picked[0] != '\0')
							{
								std::stringstream ssPaths(picked);
								std::string path;
								while (std::getline(ssPaths, path, '|'))
								{
									std::string universalPath(path);
									std::replace(universalPath.begin(), universalPath.end(), '\\', '/');

									// Create the asset reference
									AssetReferencePtr assetRef= assetRefFactory->allocateAssetReference();
									if (assetRef)
									{
										// Assign path to the asset
										assetRef->setAssetPath(universalPath);

										// Register the asset reference with the graph
										nodeGraph->getAssetReferencesMutable().push_back(assetRef);
										onAssetReferenceCreated(assetRef);
									}
								}
							}
						}
						ImGui::SameLine();
					}
				}

				ImGui::SetCursorPosY(ImGui::GetCursorPosY() + 18);
				ImGui::Separator();

				// Assets browser
				if (nodeGraph)
				{
					auto& assetRefArray= nodeGraph->getAssetReferences();

					MkGuiScopedChild assetBrowser("AssetBrowser");

					ImGui::Dummy(ImVec2(1, 10));
					for (int assetIndex= 0; assetIndex < assetRefArray.size(); assetIndex++)
					{
						AssetReferencePtr assetRefPtr= assetRefArray[assetIndex];

						ImGui::Dummy(ImVec2(10, 140));
						ImGui::SameLine();
						{
							MkGuiScopedGroup assetGroup;
							std::string idStr= "##asset" + std::to_string(assetIndex);
							ImGui::Button(idStr.c_str(), ImVec2(120, 140));

							{
								MkGuiScopedDragDropSource dds(ImGuiDragDropFlags_None);
								if (dds)
								{
									ImGui::SetDragDropPayload(assetRefPtr->getClassName().c_str(), &assetRefPtr,
															  sizeof(AssetReferencePtr));
									ImGui::TextUnformatted(assetRefPtr->getShortName().c_str());
								}
							}

							// Context menu
							bool itemDeleted= false;
							{
								MkGuiScopedStyle assetContextMenuStyle(
									m_styleManager->getStyle("node_editor_context_menu"));
								MkGuiScopedPopupContextItem assetContextMenu;
								if (assetContextMenu)
								{
									ImNodes::ClearLinkSelection();
									ImNodes::ClearNodeSelection();

									m_objectSelection= GraphObjectSelection(GraphObjectIdType::ASSET, 1);
									m_objectSelection.setObjectId(0, assetIndex);

									if (ImGui::MenuItem(locLabel("nodeEditor.delete"), ICON_FK_TRASH, "DELETE"))
									{
										deleteSelectedItem();
										itemDeleted= true;
									}
								}
							}

							if (!itemDeleted)
							{
								IMkTexturePtr texture= assetRefPtr->getPreviewTexture();

								ImGui::SetCursorPosX(ImGui::GetCursorPosX() + 10);
								ImGui::SetCursorPosY(ImGui::GetCursorPosY() - 130);

								if (texture && texture->getGlTextureId() != 0)
								{
									ImGui::Image((void*)(intptr_t)texture->getGlTextureId(), ImVec2(100, 100));
								}
								ImGui::Dummy(ImVec2(2, 1));
								ImGui::SameLine();
								ImGui::SetNextItemWidth(108);
								ImGui::TextUnformatted(assetRefPtr->getShortName().c_str());
							}
						}

						ImGui::SameLine();
						if (ImGui::GetContentRegionAvail().x < 130)
						{
							ImGui::NewLine();
							ImGui::NewLine();
						}
					}
					ImGui::NewLine();
					ImGui::Dummy(ImVec2(1, 10));
				}
			}
		}
	}
}

void NodeEditorWindow::renderSelectedObjectPanel()
{
	ImGui::SameLine();
	MkGuiScopedChild rightPanel("Right Panel", ImVec2(344, ImGui::GetContentRegionAvail().y));

	if (m_objectSelection.getObjectIdType() == GraphObjectIdType::NODE)
	{
		NodePtr node= getNodeGraph()->getNodeById(m_objectSelection.getObjectId(0));

		if (node)
		{
			node->editorRenderPropertySheet(m_editorState);
		}
	}
	else if (m_objectSelection.getObjectIdType() == GraphObjectIdType::ASSET)
	{
		const int assetIndex= m_objectSelection.getObjectId(0);
		const std::vector<AssetReferencePtr>& assetArray= getNodeGraph()->getAssetReferences();

		if (assetIndex >= 0 && assetIndex < (int)assetArray.size())
		{
			assetArray[assetIndex]->editorRenderPropertySheet(m_editorState);
		}
	}
	else if (m_objectSelection.getObjectIdType() == GraphObjectIdType::VARIABLE)
	{
		GraphPropertyPtr property= getNodeGraph()->getPropertyById(m_objectSelection.getObjectId(0));

		if (property)
		{
			property->editorRenderPropertySheet(m_editorState);
		}
	}
}

void NodeEditorWindow::deleteSelectedItem()
{
	if (m_objectSelection.getObjectIdType() == GraphObjectIdType::NODE)
	{
		for (int i= 0; i < m_objectSelection.getObjectCount(); i++)
		{
			const t_node_id nodeId= m_objectSelection.getObjectId(i);
			NodePtr node= getNodeGraph()->getNodeById(nodeId);

			if (node && node->editorCanDelete())
			{
				getNodeGraph()->deleteNodeById(nodeId);
			}
		}

		m_objectSelection.clear();
	}
	else if (m_objectSelection.getObjectIdType() == GraphObjectIdType::LINK)
	{
		for (int i= 0; i < m_objectSelection.getObjectCount(); i++)
		{
			const t_node_link_id linkId= m_objectSelection.getObjectId(i);

			getNodeGraph()->deleteLinkById(linkId);
		}

		m_objectSelection.clear();
	}
	else if (m_objectSelection.getObjectIdType() == GraphObjectIdType::VARIABLE)
	{
		for (int i= 0; i < m_objectSelection.getObjectCount(); i++)
		{
			const t_graph_property_id propertyId= m_objectSelection.getObjectId(i);

			getNodeGraph()->deletePropertyById(propertyId);
		}

		m_objectSelection.clear();
	}
	else if (m_objectSelection.getObjectIdType() == GraphObjectIdType::ASSET && m_objectSelection.getObjectCount() > 0)
	{
		const std::vector<AssetReferencePtr>& assetList= getNodeGraph()->getAssetReferences();
		const int assetIndex= m_objectSelection.getObjectId(0);

		if (assetIndex >= 0 && assetIndex < (int)assetList.size())
		{
			getNodeGraph()->deleteAssetReference(assetList[assetIndex]);
		}
		m_objectSelection.clear();
	}
}

NodeGraphFactoryPtr NodeEditorWindow::getNodeGraphFactory() const { return std::make_shared<NodeGraphFactory>(); }

void NodeEditorWindow::newGraph()
{
	// Push this window's GL context before graph resource creation (VAOs, VBOs).
	// Graph creation may be triggered while a different window's context is current
	// (e.g. when bindCompositorComponent is called after createAppWindowInternal pops
	// the editor window's context). VAOs are not shared between GL contexts.
	auto* ownerApp= getOwnerApp();
	auto* windowContext= m_mkWindowContext.get();
	ownerApp->getWindowManager()->pushCurrentWindowContext(windowContext);

	m_editorState.nodeGraph= getNodeGraphFactory()->initialCreateNodeGraph(this);

	ownerApp->getWindowManager()->popCurrentWindowContext(windowContext);

	onNodeGraphCreated();

	if (m_editorState.nodeGraph)
	{
		m_history.reset(m_editorState.nodeGraph->saveToSnapshotString());
	}
}

bool NodeEditorWindow::loadGraph(const std::filesystem::path& path)
{
	// Push this window's GL context before graph resource creation (VAOs, VBOs).
	// See comment in newGraph() for details.
	auto* ownerApp= getOwnerApp();
	auto* windowContext= m_mkWindowContext.get();
	ownerApp->getWindowManager()->pushCurrentWindowContext(windowContext);

	m_editorState.nodeGraph= NodeGraphFactory::loadNodeGraph(this, path);

	ownerApp->getWindowManager()->popCurrentWindowContext(windowContext);

	if (m_editorState.nodeGraph)
	{
		m_editorState.nodeGraphPath= path;
		onNodeGraphCreated();
		m_history.reset(m_editorState.nodeGraph->saveToSnapshotString());
		return true;
	}
	else
	{
		MIKAN_LOG_ERROR("NodeEditorWindow::load") << "Failed to load node graph: " << path;
	}

	return false;
}

bool NodeEditorWindow::saveGraph(bool bShowFileDialog)
{
	auto resolvedPath= PathUtils::resolveProjectResource(m_editorState.nodeGraphPath);

	// If no path was set (or non resolved) or we explicitly want to show the file dialog,
	// bring up the save path dialog
	if (resolvedPath.empty() || bShowFileDialog)
	{
		std::string defautPath= (PathUtils::getProjectDirectory() / "graphs" / "new_graph.graph").string();
		const char* filterItems[1]= {"*.graph"};
		const char* filterDesc= locText("nodeEditor.graphFilesFilterDescription");

		const char* picked= tinyfd_saveFileDialog(locText("nodeEditor.saveCompositorGraphDialogTitle"),
												  defautPath.c_str(), 1, filterItems, filterDesc);

		if (picked != nullptr && picked[0] != '\0')
		{
			m_editorState.nodeGraphPath= picked;
			resolvedPath= picked;
		}
	}

	if (!resolvedPath.empty() && m_editorState.nodeGraph)
	{
		NodeGraphFactory::saveNodeGraph(resolvedPath, m_editorState.nodeGraph);
		return true;
	}

	return false;
}

void NodeEditorWindow::undo()
{
	// Applied at the top of the next update, outside the ImGui frame
	m_pendingHistorySteps-= 1;
}

void NodeEditorWindow::redo() { m_pendingHistorySteps+= 1; }

bool NodeEditorWindow::stepHistory(int steps)
{
	// Walk the cursor first so a multi-step request rebuilds the graph once
	const std::string* targetSnapshot= nullptr;
	while (steps != 0)
	{
		const std::string* snapshot= (steps < 0) ? m_history.undo() : m_history.redo();
		if (snapshot == nullptr)
		{
			break;
		}

		targetSnapshot= snapshot;
		steps+= (steps < 0) ? 1 : -1;
	}

	if (targetSnapshot == nullptr)
	{
		return false;
	}

	return restoreGraphSnapshot(*targetSnapshot);
}

bool NodeEditorWindow::restoreGraphSnapshot(const std::string& snapshot)
{
	m_bApplyingHistory= true;

	// Push this window's GL context before graph resource creation (VAOs, VBOs).
	// See comment in newGraph() for details.
	auto* ownerApp= getOwnerApp();
	auto* windowContext= m_mkWindowContext.get();
	ownerApp->getWindowManager()->pushCurrentWindowContext(windowContext);

	NodeGraphPtr restoredGraph= NodeGraphFactory::loadNodeGraphFromSnapshotString(this, snapshot);

	ownerApp->getWindowManager()->popCurrentWindowContext(windowContext);

	if (!restoredGraph)
	{
		MIKAN_LOG_ERROR("NodeEditorWindow::restoreGraphSnapshot") << "Failed to rebuild graph from snapshot";
		m_bApplyingHistory= false;
		return false;
	}

	// Swap in the restored graph using the same window plumbing a load uses
	onNodeGraphDeleted();
	m_editorState.nodeGraph= restoredGraph;
	m_editorState.startedLinkPinId= -1;
	m_editorState.bLinkHanged= false;
	onNodeGraphCreated();

	// Stale selections may reference objects the snapshot does not contain
	{
		MkGuiScopedContext scopedContext(*m_guiContext.get());
		ImNodes::ClearNodeSelection();
		ImNodes::ClearLinkSelection();
	}
	m_objectSelection.clear();

	// Let subclasses rebind the restored graph to its owning component
	onGraphRestored();

	m_bCheckpointPending= false;
	m_bApplyingHistory= false;

	return true;
}

void NodeEditorWindow::updateHistoryCapture()
{
	if (m_bApplyingHistory)
	{
		return;
	}

	// Edits with no graph delegate (node property sheets, node drags) surface
	// as a widget going inactive or a mouse release; commit dedup drops false triggers
	const bool bAnyItemActive= ImGui::IsAnyItemActive();
	if ((m_bAnyItemActiveLastFrame && !bAnyItemActive) || ImGui::IsMouseReleased(ImGuiMouseButton_Left))
	{
		m_bCheckpointPending= true;
	}
	m_bAnyItemActiveLastFrame= bAnyItemActive;

	// Commit once the interaction settles, coalescing a burst (a delete
	// cascade, a whole drag) into a single undo step
	if (m_bCheckpointPending && !bAnyItemActive && !ImGui::IsMouseDown(ImGuiMouseButton_Left))
	{
		NodeGraphPtr nodeGraph= getNodeGraph();
		if (nodeGraph)
		{
			m_history.commit(nodeGraph->saveToSnapshotString());
		}
		m_bCheckpointPending= false;
	}
}

void NodeEditorWindow::enqueueAutomationTask(std::function<void()>&& task)
{
	m_automationTasks.push_back(std::move(task));
}

void NodeEditorWindow::flushAutomationTasks()
{
	while (!m_automationTasks.empty())
	{
		std::function<void()> task= std::move(m_automationTasks.front());
		m_automationTasks.erase(m_automationTasks.begin());
		task();
	}
}

bool NodeEditorWindow::wantsDestroy() const { return m_bCloseRequested || EditorWindow::wantsDestroy(); }

bool NodeEditorWindow::automationCreateNode(const std::string& nodeClassName, const glm::vec2& gridPos,
											t_node_id& outNodeId, std::string& outError)
{
	NodeGraphPtr nodeGraph= getNodeGraph();
	if (!nodeGraph)
	{
		outError= "no graph loaded";
		return false;
	}

	NodeFactoryPtr nodeFactory= nodeGraph->getNodeFactory(nodeClassName);
	if (!nodeFactory)
	{
		outError= "unknown node class '" + nodeClassName + "'";
		return false;
	}

	// Node creation touches GL resources and, via onNodeCreated, ImNodes state
	auto* ownerApp= getOwnerApp();
	auto* windowContext= m_mkWindowContext.get();
	ownerApp->getWindowManager()->pushCurrentWindowContext(windowContext);
	NodePtr newNode;
	{
		MkGuiScopedContext scopedContext(*m_guiContext.get());

		m_editorState.hangPosGridSpace= ImVec2(gridPos.x, gridPos.y);
		newNode= nodeGraph->createNode(nodeFactory, m_editorState);
	}
	ownerApp->getWindowManager()->popCurrentWindowContext(windowContext);

	if (!newNode)
	{
		outError= "node creation failed";
		return false;
	}

	outNodeId= newNode->getId();
	return true;
}

bool NodeEditorWindow::automationDeleteNode(t_node_id nodeId, std::string& outError)
{
	NodeGraphPtr nodeGraph= getNodeGraph();
	if (!nodeGraph)
	{
		outError= "no graph loaded";
		return false;
	}

	NodePtr node= nodeGraph->getNodeById(nodeId);
	if (!node)
	{
		outError= "no node with id " + std::to_string(nodeId);
		return false;
	}

	if (!node->editorCanDelete())
	{
		outError= "node " + std::to_string(nodeId) + " is not deletable";
		return false;
	}

	auto* ownerApp= getOwnerApp();
	auto* windowContext= m_mkWindowContext.get();
	ownerApp->getWindowManager()->pushCurrentWindowContext(windowContext);
	{
		MkGuiScopedContext scopedContext(*m_guiContext.get());

		nodeGraph->deleteNodeById(nodeId);
	}
	ownerApp->getWindowManager()->popCurrentWindowContext(windowContext);

	return true;
}

bool NodeEditorWindow::automationCreateLink(t_node_pin_id startPinId, t_node_pin_id endPinId, t_node_link_id& outLinkId,
											std::string& outError)
{
	NodeGraphPtr nodeGraph= getNodeGraph();
	if (!nodeGraph)
	{
		outError= "no graph loaded";
		return false;
	}

	NodePinPtr startPin= nodeGraph->getPinById(startPinId);
	if (!startPin)
	{
		outError= "no pin with id " + std::to_string(startPinId);
		return false;
	}

	NodePinPtr endPin= nodeGraph->getPinById(endPinId);
	if (!endPin)
	{
		outError= "no pin with id " + std::to_string(endPinId);
		return false;
	}

	if (!startPin->canPinsBeConnected(endPin))
	{
		outError= "pins " + std::to_string(startPinId) + " and " + std::to_string(endPinId) + " cannot connect";
		return false;
	}

	auto* ownerApp= getOwnerApp();
	auto* windowContext= m_mkWindowContext.get();
	ownerApp->getWindowManager()->pushCurrentWindowContext(windowContext);
	NodeLinkPtr link;
	{
		MkGuiScopedContext scopedContext(*m_guiContext.get());

		link= nodeGraph->createLink(startPinId, endPinId);
	}
	ownerApp->getWindowManager()->popCurrentWindowContext(windowContext);

	if (!link)
	{
		outError= "link creation failed";
		return false;
	}

	outLinkId= link->getId();
	return true;
}

bool NodeEditorWindow::automationDeleteLink(t_node_link_id linkId, std::string& outError)
{
	NodeGraphPtr nodeGraph= getNodeGraph();
	if (!nodeGraph)
	{
		outError= "no graph loaded";
		return false;
	}

	if (!nodeGraph->getLinkById(linkId))
	{
		outError= "no link with id " + std::to_string(linkId);
		return false;
	}

	auto* ownerApp= getOwnerApp();
	auto* windowContext= m_mkWindowContext.get();
	ownerApp->getWindowManager()->pushCurrentWindowContext(windowContext);
	{
		MkGuiScopedContext scopedContext(*m_guiContext.get());

		nodeGraph->deleteLinkById(linkId);
	}
	ownerApp->getWindowManager()->popCurrentWindowContext(windowContext);

	return true;
}

void NodeEditorWindow::onNodeGraphCreated()
{
	MkGuiScopedContext scopedContext(*m_guiContext.get());
	NodeGraphPtr graph= getNodeGraph();

	graph->OnNodeCreated+= MakeDelegate(this, &NodeEditorWindow::onNodeCreated);
	graph->OnNodeDeleted+= MakeDelegate(this, &NodeEditorWindow::onNodeDeleted);
	graph->OnLinkCreated+= MakeDelegate(this, &NodeEditorWindow::onLinkCreated);
	graph->OnLinkDeleted+= MakeDelegate(this, &NodeEditorWindow::onLinkDeleted);
	graph->OnPinCreated+= MakeDelegate(this, &NodeEditorWindow::onPinCreated);
	graph->OnPinDeleted+= MakeDelegate(this, &NodeEditorWindow::onPinDeleted);
	graph->OnPropertyCreated+= MakeDelegate(this, &NodeEditorWindow::onGraphPropertyCreated);
	graph->OnPropertyModifed+= MakeDelegate(this, &NodeEditorWindow::onGraphPropertyModified);
	graph->OnPropertyDeleted+= MakeDelegate(this, &NodeEditorWindow::onGraphPropertyDeleted);
	graph->OnAssetReferenceDeleted+= MakeDelegate(this, &NodeEditorWindow::onAssetReferenceDeleted);

	// Register the node positions with ImNode
	for (auto iter= graph->getNodesMap().begin(); iter != graph->getNodesMap().end(); iter++)
	{
		const t_node_id nodeId= iter->first;
		NodePtr node= iter->second;

		const glm::vec2& nodePos= node->getNodePos();
		ImNodes::SetNodeGridSpacePos(nodeId, {nodePos.x, nodePos.y});
	}
}

void NodeEditorWindow::onNodeGraphDeleted()
{
	NodeGraphPtr graph= getNodeGraph();

	if (graph)
	{
		graph->OnNodeCreated-= MakeDelegate(this, &NodeEditorWindow::onNodeCreated);
		graph->OnNodeDeleted-= MakeDelegate(this, &NodeEditorWindow::onNodeDeleted);
		graph->OnLinkCreated-= MakeDelegate(this, &NodeEditorWindow::onLinkCreated);
		graph->OnLinkDeleted-= MakeDelegate(this, &NodeEditorWindow::onLinkDeleted);
		graph->OnPinCreated-= MakeDelegate(this, &NodeEditorWindow::onPinCreated);
		graph->OnPinDeleted-= MakeDelegate(this, &NodeEditorWindow::onPinDeleted);
		graph->OnPropertyCreated-= MakeDelegate(this, &NodeEditorWindow::onGraphPropertyCreated);
		graph->OnPropertyModifed-= MakeDelegate(this, &NodeEditorWindow::onGraphPropertyModified);
		graph->OnPropertyDeleted-= MakeDelegate(this, &NodeEditorWindow::onGraphPropertyDeleted);
		graph->OnAssetReferenceDeleted-= MakeDelegate(this, &NodeEditorWindow::onAssetReferenceDeleted);
	}
}

void NodeEditorWindow::onNodeCreated(t_node_id id)
{
	// Set the initial position of the node using the current editor mouse position
	const ImVec2& hangPosGridSpace= m_editorState.hangPosGridSpace;
	ImNodes::SetNodeGridSpacePos(id, hangPosGridSpace);
	NodePtr node= getNodeGraph()->getNodeById(id);
	if (node)
	{
		node->setNodePos(glm::vec2(hangPosGridSpace.x, hangPosGridSpace.y));
	}

	// Make the newly created node selected
	m_objectSelection= GraphObjectSelection(GraphObjectIdType::NODE, 1);
	m_objectSelection.setObjectId(0, id);

	ImNodes::ClearLinkSelection();
	ImNodes::ClearNodeSelection();
	ImNodes::SelectNode(id);

	markHistoryCheckpoint();
}

void NodeEditorWindow::onNodeDeleted(t_node_id id)
{
	if (m_objectSelection.getObjectIdType() == GraphObjectIdType::NODE && m_objectSelection.removeObjectId(id))
	{
		ImNodes::ClearNodeSelection();
	}

	markHistoryCheckpoint();
}

void NodeEditorWindow::onLinkCreated(t_node_link_id id) { markHistoryCheckpoint(); }

void NodeEditorWindow::onLinkDeleted(t_node_link_id id)
{
	if (m_objectSelection.getObjectIdType() == GraphObjectIdType::LINK && m_objectSelection.removeObjectId(id))
	{
		ImNodes::ClearLinkSelection();
	}

	markHistoryCheckpoint();
}

void NodeEditorWindow::onPinCreated(t_node_pin_id id) { markHistoryCheckpoint(); }

void NodeEditorWindow::onPinDeleted(t_node_pin_id id) { markHistoryCheckpoint(); }

void NodeEditorWindow::onGraphPropertyCreated(t_graph_property_id id) { markHistoryCheckpoint(); }

void NodeEditorWindow::onGraphPropertyModified(t_graph_property_id id) { markHistoryCheckpoint(); }

void NodeEditorWindow::onGraphPropertyDeleted(t_graph_property_id id) { markHistoryCheckpoint(); }

void NodeEditorWindow::onAssetReferenceCreated(AssetReferencePtr assetRef) { markHistoryCheckpoint(); }

void NodeEditorWindow::onAssetReferenceDeleted(AssetReferencePtr assetRef) { markHistoryCheckpoint(); }

void NodeEditorWindow::shutdown()
{
	// Run parked automation work so its deferred replies still send
	flushAutomationTasks();

	onNodeGraphDeleted();
	m_editorState.nodeGraph= nullptr;
	m_editorState.nodeGraphPath.clear();

	shutdownTextureCache();
	shutdownModelResourceManager();
	shutdownStyleManager();
	shutdownGuiContext();
	shutdownWindow();
}

// -- IMkWindowEventListener
bool NodeEditorWindow::onWindowEvent(const MkWindowEvent& event) { return m_guiContext->onWindowEvent(event); }
