//-- includes -----
#include "NodeEditorWindow.h"
#include "Logger.h"
#include "MkGuiContext.h"
#include "MkGuiScopedStyle.h"
#include "MkGuiStyleManager.h"
#include "MkGuiScopedUpdate.h"
#include "MkGuiScopedContext.h"
#include "MkGuiScopedChild.h"
#include "MkGuiScopedWindow.h"
#include "MkGuiScopedGroup.h"
#include "MkGuiScopedPopup.h"
#include "MkGuiScopedTabBar.h"
#include "MkGuiScopedTabItem.h"
#include "MkGuiScopedDragDropSource.h"
#include "MkGuiScopedDragDropTarget.h"
#include "MkNodesScopedNodeEditor.h"

#include "App.h"
#include "AssetReference.h"
#include "SdlCommon.h"
#include "MikanModelResourceManager.h"
#include "IMkViewport.h"
#include "MkStateStack.h"
#include "IMkState.h"
#include "MainWindow.h"
#include "MkStateModifiers.h"
#include "MikanShaderCache.h"
#include "IMkTexture.h"
#include "MikanTextureCache.h"
#include "Graphs/NodeGraph.h"
#include "Graphs/NodeEvaluator.h"
#include "Nodes/Node.h"
#include "NodeEditorUI.h"
#include "PathUtils.h"
#include "SdlManager.h"
#include "SdlWindow.h"
#include "StringUtils.h"
#include "TextStyle.h"

#include "Pins/NodePin.h"

#include "imgui.h"
#include "imnodes.h"

// Autogenerated header containing Unicode Icon IDs from "forkawesome-webfont.ttf"
#include "IconsForkAwesome.h"

#include "tinyfiledialogs.h" // Cross-platform file dialogs library

#include <easy/profiler.h>

#include "glm/ext/vector_float4.hpp"

// Drag-Drop Payload Types
#define DRAG_DROP_TYPE_VARIABLE		"Variable"
#define DRAG_DROP_TYPE_ASSET_REF	"Asset"

//-- public methods -----
NodeEditorWindow::NodeEditorWindow(App* ownerApp)
	: m_ownerApp(ownerApp)
	, m_sdlWindow(SdlWindowUniquePtr(new SdlWindow(this)))
	, m_mkStateStack(MkStateStackUniquePtr(new MkStateStack(this)))
	, m_modelResourceManager(MikanModelResourceManagerUniquePtr(new MikanModelResourceManager(this)))
	, m_shaderCache(MikanShaderCacheUniquePtr(new MikanShaderCache(this)))
	, m_textureCache(MikanTextureCacheUniquePtr(new MikanTextureCache(this)))
{}

NodeEditorWindow::~NodeEditorWindow()
{
}

IMkLineRenderer* NodeEditorWindow::getLineRenderer()
{
	return nullptr;
}

IMkTextRenderer* NodeEditorWindow::getTextRenderer()
{
	return nullptr;
}

MikanModelResourceManager* NodeEditorWindow::getModelResourceManager()
{
	return m_modelResourceManager.get();
}

IMkShaderCache* NodeEditorWindow::getShaderCache()
{
	return m_shaderCache.get();
}

IMkTextureCache* NodeEditorWindow::getTextureCache()
{
	return m_textureCache.get();
}

MkStateStack& NodeEditorWindow::getMkStateStack()
{
	return *m_mkStateStack.get();
}

SdlWindow& NodeEditorWindow::getSdlWindow()
{
	return *m_sdlWindow.get();
}

// -- IMkWindow ----
bool NodeEditorWindow::startup()
{
	EASY_FUNCTION();

	bool success = true;

	MIKAN_LOG_INFO("NodeEditorWindow::init()") << "Initializing NodeEditorWindow";

	static const int k_node_window_pixel_width = 1080;
	static const int k_node_window_pixel_height = 720;

	auto windowTitle = "Node Editor";
	m_sdlWindow
		->enableGLDataSharing() // Want access to video textures owned by MainWindow's GL Context
		->setTitle(windowTitle)
		->setSize(k_node_window_pixel_width, k_node_window_pixel_height);
	if (!m_sdlWindow->startup())
	{
		MIKAN_LOG_ERROR("NodeEditorWindow::startup") << "Unable to initialize main SDK window: ";
		success = false;
	}

	// Setup ImGui/ImNodes context
	if (success)
	{
		m_guiContext = std::make_shared<MkGuiContext>(
			m_sdlWindow->getInternalSdlWindow(),
			m_sdlWindow->getInternalGlContext());
		if (!m_guiContext->startup())
		{
			MIKAN_LOG_ERROR("NodeEditorWindow::startup") << "Unable to create GUI context";
			success = false;
		}
	}

	if (success)
	{
		m_styleManager = std::make_unique<MkGuiStyleManager>();
		const auto stylesPath = PathUtils::getResourceDirectory() / "gui_styles";
		if (!m_styleManager->startup(m_guiContext.get(), stylesPath))
		{
			MIKAN_LOG_ERROR("NodeEditorWindow::startup") << "Failed to initialize style manager";
			success = false;
		}
		else
		{
			m_editorState.styleManager = m_styleManager.get();
		}
	}

	if (success && !m_textureCache->startup())
	{
		MIKAN_LOG_ERROR("NodeEditorWindow::startup") << "Failed to initialize texture cache!";
		success = false;
	}

	if (success && !m_shaderCache->startup())
	{
		MIKAN_LOG_ERROR("NodeEditorWindow::startup") << "Failed to initialize shader cache!";
		success = false;
	}

	if (success)
	{
		if (!m_modelResourceManager->startup())
		{
			MIKAN_LOG_ERROR("NodeEditorWindow::init") << "Unable to initialize model resource manager";
			success = false;
		}
	}

	if (success)
	{
		// Set default state flags at the base of the stack
		IMkState* mkBaseState= m_mkStateStack->pushState("NodeEditor Root Scope");
		assert(mkBaseState->getStackDepth() == 0);

		mkBaseState
		->enableFlag(eMkStateFlagType::texture2d)
		->enableFlag(eMkStateFlagType::depthTest)
		->disableFlag(eMkStateFlagType::cullFace);

		static const glm::vec4 k_clear_color = glm::vec4(0.45f, 0.45f, 0.5f, 1.f);
		mkStateSetClearColor(mkBaseState, k_clear_color);
	}

	return success;
}

void NodeEditorWindow::update(float deltaSeconds)
{
	EASY_FUNCTION();

	// Push the ImGui Update scope
	MkGuiScopedUpdate scopedCtx(*m_guiContext);

	// Process most recent SDL events (keyboard, mouse, etc)
	m_sdlWindow->handleSDLEvents(this);

	// Process UI input and build ImGui draw lists
	updateUI();

	// On Pop: Finalize draw lists and clear ImGui context
}

void NodeEditorWindow::render()
{
	EASY_FUNCTION();

	// Clear the window
	m_sdlWindow->renderBegin();

	{
		// Create a scoped UI rendering settings
		MkScopedState scopedState = m_mkStateStack->createScopedState("appStage renderUI");
		IMkState* glState = scopedState.getStackState();

		mkStateSetViewport(glState, 0, 0, m_sdlWindow->getWidth(), m_sdlWindow->getHeight());

		// Submit the MkGui draw calls
		m_guiContext->submitDrawData();
	}

	// Call SDL_GL_SwapWindow
	m_sdlWindow->renderEnd();
}

void NodeEditorWindow::updateUI()
{
	MkGuiScopedStyle baseStyle(m_styleManager->getStyle("node_editor_base"));

	ImGui::SetNextWindowSize(ImVec2(getWidth(), getHeight()), ImGuiCond_Once);
	MkGuiScopedWindow nodeEditorWindow("Node Editor", nullptr,
		ImGuiWindowFlags_NoResize |
		ImGuiWindowFlags_NoBringToFrontOnFocus |
		ImGuiWindowFlags_NoMove);

	// Toolbar
	renderToolbar();

	// Left Panel
	renderGraphVariablesPanel();

	ImGui::SameLine();
	{
		MkGuiScopedChild mainPanel("Main Panel", ImVec2(ImGui::GetContentRegionAvail().x - 250,
		                                                ImGui::GetContentRegionAvail().y));

		// Main Frame
		renderMainFrame();

		// Bottom Panel
		renderAssetsPanel();
	}

	// Right Panel
	renderSelectedObjectPanel();
}

void NodeEditorWindow::renderMainFrame()
{
	NodeGraphPtr nodeGraph= getNodeGraph();

	{
		MkGuiScopedChild mainChild("Main", ImVec2(ImGui::GetContentRegionAvail().x,
												   ImGui::GetContentRegionAvail().y - 226));
		{
			MkNodesScopedNodeEditor nodeEditor;

			if (nodeGraph)
			{
				nodeGraph->editorRender(m_editorState);
			}
		}
	}

	// Draw error messages on top of related nodes
	renderNodeEvalErrors();

	// Node selection
	if (ImNodes::NumSelectedNodes() > 0)
	{
		GraphObjectSelection selection(GraphObjectIdType::NODE, ImNodes::NumSelectedNodes());

		ImNodes::GetSelectedNodes(selection.getRawObjectArray());
		m_objectSelection= selection;
	}

	// Start link
	if (ImNodes::IsLinkStarted(&m_editorState.startedLinkPinId))
	{
		NodePinPtr pinPtr= getNodeGraph()->getPinById(m_editorState.startedLinkPinId);
		if (pinPtr)
		{
			ImNodes::GetStyle().Colors[ImNodesCol_Link] = pinPtr->editorGetLinkStyleColor();
		}
	}

	// Drop link
	if (ImNodes::IsLinkDropped())
	{
		ImGui::OpenPopup("editor_context_menu_nodes");
		m_editorState.bLinkHanged = true;
		m_editorState.hangPosGridSpace = NodeEditorUI::MousePosToGridSpace();
	}

	// Link creation
	int startPinId, endPinId;
	if (ImNodes::IsLinkCreated(&startPinId, &endPinId))
	{
		m_editorState.startedLinkPinId = -1;
		getNodeGraph()->createLink(startPinId, endPinId);
	}

	// Context menu
	renderMainFrameContextMenu(m_editorState);

	// Drag and drop creation
	{
		NodeEditorState editorStateCopy = m_editorState;
		editorStateCopy.hangPosGridSpace = NodeEditorUI::MousePosToGridSpace();

		handleMainFrameDragDrop(editorStateCopy);
	}

	// Delete key event (and not focused on a text input)
	if (ImGui::IsKeyPressed(ImGuiKey_Delete, false) && !ImGui::IsAnyItemActive())
	{
		deleteSelectedItem();
	}
}

void NodeEditorWindow::renderNodeEvalErrors()
{
	if (m_editorState.nodeGraph && m_lastNodeEvalErrors.size() > 0)
	{
		size_t errorIter= 0;
		while (errorIter < m_lastNodeEvalErrors.size())
		{
			const NodeEvaluationError* currentError= &m_lastNodeEvalErrors[errorIter];
			const std::string evalWindowId= StringUtils::stringify("Eval Error##Node", currentError->errorNodeId);

			static const float k_errorWindowOffset = 50.f;
			ImVec2 errorPos = 
				currentError->errorNodeId != -1 
				? ImNodes::GetNodeScreenSpacePos(currentError->errorNodeId)
				: ImVec2(0, 0);
			errorPos.y -= k_errorWindowOffset;

			ImGui::SetNextWindowPos(errorPos);
			MkGuiScopedWindow evalWindow(
				evalWindowId.c_str(),
				nullptr,
				ImGuiWindowFlags_NoResize | ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoNav);
			{
				MkGuiScopedGroup errorGroup;
				MkGuiScopedStyle errorTextStyle(m_styleManager->getStyle("node_editor_error_text"));
				while (errorIter < m_lastNodeEvalErrors.size())
				{
					// Add a bullet point for each error on the same node
					ImGui::BulletText(currentError->errorMessage.c_str());

					// Advance to the next error message on this node
					errorIter++;

					// If the next error is on a different node, move on to the next error window
					if (errorIter < m_lastNodeEvalErrors.size())
					{
						const NodeEvaluationError* nextError= &m_lastNodeEvalErrors[errorIter];

						if (nextError->errorNodeId == currentError->errorNodeId)
						{
							currentError= nextError;
						}
						else
						{
							break;
						}
					}
				}
			}
		}
	}
}

void NodeEditorWindow::renderMainFrameContextMenu(const NodeEditorState& editorState)
{
	if (ImGui::GetMouseDragDelta(ImGuiMouseButton_Right).x == 0.0f
		&& ImGui::GetMouseDragDelta(ImGuiMouseButton_Right).y == 0.0f
		&& ImGui::IsMouseReleased(ImGuiMouseButton_Right)
		&& ImGui::IsWindowHovered(ImGuiHoveredFlags_ChildWindows))
	{
		int id = -1;
		if (ImNodes::IsNodeHovered(&id))
		{
			ImNodes::ClearNodeSelection();
			ImNodes::ClearLinkSelection();
			ImNodes::SelectNode(id);
			m_objectSelection= GraphObjectSelection(GraphObjectIdType::NODE, 1);
			m_objectSelection.setObjectId(0, id);
			ImGui::OpenPopup("editor_context_menu_node");
		}
		else if (ImNodes::IsLinkHovered(&id))
		{
			ImNodes::ClearNodeSelection();
			ImNodes::ClearLinkSelection();
			ImNodes::SelectLink(id);
			m_objectSelection = GraphObjectSelection(GraphObjectIdType::LINK, 1);
			m_objectSelection.setObjectId(0, id);
			ImGui::OpenPopup("editor_context_menu_link");
		}
		else
		{
			ImGui::OpenPopup("editor_context_menu_nodes");
			m_editorState.hangPosGridSpace = NodeEditorUI::MousePosToGridSpace();
		}
	}

	MkGuiScopedStyle contextMenuStyle(m_styleManager->getStyle("node_editor_context_menu"));
	{
		MkGuiScopedPopup nodePopup("editor_context_menu_node");
		if (nodePopup)
		{
			NodePtr node;
			if (m_objectSelection.getObjectIdType() == GraphObjectIdType::NODE)
			{
				node= getNodeGraph()->getNodeById(m_objectSelection.getObjectId(0));
			}

			if (node && node->editorCanDelete())
			{
				if (ImGui::MenuItem("Delete", ICON_FK_TRASH, "DELETE"))
				{
					getNodeGraph()->deleteNodeById(m_objectSelection.getObjectId(0));
				}
			}
			else
			{
				ImGui::CloseCurrentPopup();
			}
		}
		else
		{
			MkGuiScopedPopup linkPopup("editor_context_menu_link");
			if (linkPopup)
			{
				if (m_objectSelection.getObjectIdType() == GraphObjectIdType::LINK &&
					ImGui::MenuItem("Delete", ICON_FK_TRASH, "DELETE"))
				{
					getNodeGraph()->deleteLinkById(m_objectSelection.getObjectId(0));
				}
			}
			else
			{
				MkGuiScopedPopup nodesPopup("editor_context_menu_nodes");
				if (nodesPopup)
				{
					NodeGraphPtr nodeGraph= getNodeGraph();
					if (nodeGraph)
					{
						std::vector<NodeFactoryPtr> nodeFactories = getNodeGraph()->editorGetValidNodeFactories(editorState);
						for (NodeFactoryPtr nodeFactory : nodeFactories)
						{
							const std::string nodeTitle = nodeFactory->getNodeDefaultObject()->editorGetTitle();

							if (ImGui::MenuItem(nodeTitle.c_str()))
							{
								getNodeGraph()->createNode(nodeFactory, editorState);
								break;
							}
						}
					}
				}
				else if (m_editorState.bLinkHanged)
				{
					m_editorState.bLinkHanged = false;
					m_editorState.startedLinkPinId = -1;
				}
			}
		}
	}
}

void NodeEditorWindow::renderToolbar()
{
	MkGuiScopedStyle toolbarStyle(m_styleManager->getStyle("node_editor_toolbar"));

	MkGuiScopedChild toolbarChild("Toolbar", ImVec2(ImGui::GetContentRegionAvail().x, 40));

	ImGui::SetCursorPosY((ImGui::GetWindowHeight() - 30) * 0.5f);

	if (ImGui::Button(ICON_FK_FLOPPY_O "   Save", ImVec2(0, 30)))
	{
		saveGraph(false);
	}

	// Editor Control
	{
		MkGuiScopedStyle controlPanelStyle(m_styleManager->getStyle("node_editor_control_panel"));

		ImGui::SameLine();
		MkGuiScopedChild editorControlChild("EditorControl", ImVec2(70, 30), true, ImGuiWindowFlags_NoScrollbar);
		ImGui::SetCursorPosY((ImGui::GetWindowHeight() - ImGui::GetTextLineHeight()) * 0.5f);

		ImGui::SameLine();
		{
			MkGuiScopedStyle undoStyle(m_styleManager->getStyle("node_editor_undo_button"));
			if (ImGui::SmallButton(ICON_FK_UNDO))
			{
				undo();
			}
		}
	}
}

void NodeEditorWindow::renderGraphVariablesPanel()
{
	MkGuiScopedChild leftPanel("Left Panel", ImVec2(200, ImGui::GetContentRegionAvail().y));


	// Title bar
	ImGui::SetNextItemOpen(true, ImGuiCond_Once);
	bool isNodeOpened;
	{
		MkGuiScopedStyle headerStyle(m_styleManager->getStyle("node_editor_panel_header"));
		isNodeOpened = ImGui::CollapsingHeader("Variables", ImGuiTreeNodeFlags_SpanAvailWidth);
	}

	if (isNodeOpened)
	{
		MkGuiScopedStyle selectionStyle(m_styleManager->getStyle("node_editor_variable_list"));

		auto propertyMap = getNodeGraph()->getPropertyMap();
		for (auto it = propertyMap.begin(); it != propertyMap.end(); it++)
		{
			t_graph_property_id propertyId = it->first;
			GraphPropertyPtr variable = it->second;

			// Variable
			const std::string varIcon = variable->editorGetIcon();
			const ImVec4& variconColor = variable->editorGetIconColor();
			ImGui::TextColored(variconColor, varIcon.c_str());
			ImGui::SameLine();

			const std::string varEntryName =
				StringUtils::stringify(
					variable->getName(), "##property", std::to_string(propertyId));
			bool isSelected = m_objectSelection.getObjectIdType() == GraphObjectIdType::VARIABLE;
			isSelected = isSelected && (m_objectSelection.getObjectId(0) == variable->getId());
			if (ImGui::Selectable(varEntryName.c_str(), &isSelected))
			{
				ImNodes::ClearLinkSelection();
				ImNodes::ClearNodeSelection();
				if (isSelected)
				{
					m_objectSelection = GraphObjectSelection(GraphObjectIdType::VARIABLE, 1);
					m_objectSelection.setObjectId(0, variable->getId());
				}
				else
				{
					m_objectSelection.clear();
				}
			}
			{
				MkGuiScopedDragDropSource dds(ImGuiDragDropFlags_None);
				if (dds)
				{
					ImGui::SetDragDropPayload(
						variable->getClassName().c_str(), &variable, sizeof(GraphPropertyPtr));
					ImGui::Text(variable->getName().c_str());
				}
			}

			// Context menu
			{
				MkGuiScopedStyle varContextMenuStyle(m_styleManager->getStyle("node_editor_context_menu"));
				MkGuiScopedPopupContextItem varContextMenu;
				if (varContextMenu)
				{
					ImNodes::ClearLinkSelection();
					ImNodes::ClearNodeSelection();
					m_objectSelection = GraphObjectSelection(GraphObjectIdType::VARIABLE, 1);
					m_objectSelection.setObjectId(0, variable->getId());

					if (ImGui::MenuItem("Delete", ICON_FK_TRASH, "DELETE"))
					{
						getNodeGraph()->deletePropertyById(propertyId);
						m_objectSelection.clear();
					}
				}
			}
		}
	}

	// Drag and drop creation
	{
		NodeEditorState editorStateCopy = m_editorState;
		editorStateCopy.hangPosGridSpace = NodeEditorUI::MousePosToGridSpace();

		handleGraphVariablesDragDrop(editorStateCopy);
	}

	renderNewGraphVariablesContextMenu(m_editorState);
}

void NodeEditorWindow::renderNewGraphVariablesContextMenu(const NodeEditorState& editorState)
{
	// Don't show context menu if a variable is selected
	if (m_objectSelection.hasSelectionOfType(GraphObjectIdType::VARIABLE))
		return;

	if (ImGui::GetMouseDragDelta(ImGuiMouseButton_Right).x == 0.0f
		&& ImGui::GetMouseDragDelta(ImGuiMouseButton_Right).y == 0.0f
		&& ImGui::IsMouseReleased(ImGuiMouseButton_Right)
		&& ImGui::IsWindowHovered(ImGuiHoveredFlags_ChildWindows))
	{
		ImGui::OpenPopup("editor_context_menu_nodes");
	}

	MkGuiScopedStyle newVarMenuStyle(m_styleManager->getStyle("node_editor_context_menu"));
	MkGuiScopedPopup newVarPopup("editor_context_menu_nodes");
	if (newVarPopup)
	{
		NodeGraphPtr nodeGraph = getNodeGraph();
		if (nodeGraph)
		{
			std::vector<GraphPropertyFactoryPtr> propertyFactories =
				getNodeGraph()->editorGetValidPropertyFactories(editorState);

			for (GraphPropertyFactoryPtr propertyFactory : propertyFactories)
			{
				const std::string propertyTitle = propertyFactory->getDefaultGraphPropertyObject()->editorGetTitle();

				if (ImGui::MenuItem(propertyTitle.c_str()))
				{
					GraphPropertyPtr newVariable= getNodeGraph()->createProperty(propertyFactory);

					ImNodes::ClearLinkSelection();
					ImNodes::ClearNodeSelection();

					m_objectSelection = GraphObjectSelection(GraphObjectIdType::VARIABLE, 1);
					m_objectSelection.setObjectId(0, newVariable->getId());
					break;
				}
			}
		}
	}
}

void NodeEditorWindow::renderAssetsPanel()
{
	NodeGraphPtr nodeGraph= getNodeGraph();

	MkGuiScopedChild assetsPanel("Assets Panel", ImVec2(ImGui::GetContentRegionAvail().x, 216));
	{
		MkGuiScopedTabBar assetTabBar("AssetsTabBar");
		if (assetTabBar)
		{
			MkGuiScopedStyle assetTabStyle(m_styleManager->getStyle("node_editor_asset_tab"));
			MkGuiScopedTabItem assetTabItem("Assets");
			if (assetTabItem)
			{
				MkGuiScopedChild assetSubFrame("AssetSubFrame");

				ImGui::SetCursorPos(ImVec2(ImGui::GetCursorPos().x + 6, ImGui::GetCursorPos().y + 1));

				if (nodeGraph)
				{
					auto& factoryMap = nodeGraph->getAssetReferenceFactories();
					for (auto it = factoryMap.begin(); it != factoryMap.end(); it++)
					{
						auto& assetRefFactory = it->second;
						const std::string& assetTypeName = assetRefFactory->getAssetTypeName();
						const std::string buttonName = StringUtils::stringify(ICON_FK_PLUS_CIRCLE "  Add ", assetTypeName, "##", assetTypeName);

						if (ImGui::SmallButton(buttonName.c_str()))
						{
							auto assetPath =
								tinyfd_openFileDialog(
									assetRefFactory->getFileDialogTitle(),
									assetRefFactory->getDefaultPath(),
									assetRefFactory->getFilterPatternCount(),
									assetRefFactory->getFilterPatterns(),
									assetRefFactory->getFilterDescription(),
									1);

							if (assetPath)
							{
								std::stringstream ssPaths(assetPath);
								std::string path;
								while (std::getline(ssPaths, path, '|'))
								{
									std::string universalPath(path);
									std::replace(universalPath.begin(), universalPath.end(), '\\', '/');

									// Create the asset reference
									AssetReferencePtr assetRef = assetRefFactory->allocateAssetReference();
									if (assetRef)
									{
										// Assign path to the asset
										assetRef->setAssetPath(universalPath);

										// Register the asset reference with the graph
										nodeGraph->getAssetReferencesMutable().push_back(assetRef);
										onAssetReferenceCreated(assetRef);
									}
								}
							}
						}
						ImGui::SameLine();
					}
				}

				ImGui::SetCursorPosY(ImGui::GetCursorPosY() + 18);
				ImGui::Separator();

				// Assets browser
				if (nodeGraph)
				{
					auto& assetRefArray = nodeGraph->getAssetReferences();

					MkGuiScopedChild assetBrowser("AssetBrowser");

					ImGui::Dummy(ImVec2(1, 10));
					for (int assetIndex = 0; assetIndex < assetRefArray.size(); assetIndex++)
					{
						AssetReferencePtr assetRefPtr= assetRefArray[assetIndex];

						ImGui::Dummy(ImVec2(10, 140));
						ImGui::SameLine();
						{
						MkGuiScopedGroup assetGroup;
						std::string idStr = "##asset" + std::to_string(assetIndex);
						ImGui::Button(idStr.c_str(), ImVec2(120, 140));

						{
							MkGuiScopedDragDropSource dds(ImGuiDragDropFlags_None);
							if (dds)
							{
								ImGui::SetDragDropPayload(
									assetRefPtr->getClassName().c_str(), &assetRefPtr, sizeof(AssetReferencePtr));
								ImGui::Text(assetRefPtr->getShortName().c_str());
							}
						}

						// Context menu
						bool itemDeleted = false;
						{
							MkGuiScopedStyle assetContextMenuStyle(m_styleManager->getStyle("node_editor_context_menu"));
							MkGuiScopedPopupContextItem assetContextMenu;
							if (assetContextMenu)
							{
								ImNodes::ClearLinkSelection();
								ImNodes::ClearNodeSelection();

								m_objectSelection = GraphObjectSelection(GraphObjectIdType::ASSET, assetIndex);
								m_objectSelection.setObjectId(0, assetIndex);

								if (ImGui::MenuItem("Delete", ICON_FK_TRASH, "DELETE"))
								{
									deleteSelectedItem();
									itemDeleted = true;
								}
							}
						}

						if (!itemDeleted)
						{
							IMkTexturePtr texture= assetRefPtr->getPreviewTexture();

							ImGui::SetCursorPosX(ImGui::GetCursorPosX() + 10);
							ImGui::SetCursorPosY(ImGui::GetCursorPosY() - 130);

							if (texture && texture->getGlTextureId() != 0)
							{
								ImGui::Image((void*)(intptr_t)texture->getGlTextureId(), ImVec2(100, 100));
							}
							ImGui::Dummy(ImVec2(2, 1));
							ImGui::SameLine();
							ImGui::SetNextItemWidth(108);
							ImGui::Text(assetRefPtr->getShortName().c_str());
						}
						}

						ImGui::SameLine();
						if (ImGui::GetContentRegionAvail().x < 130)
						{
							ImGui::NewLine();
							ImGui::NewLine();
						}
					}
					ImGui::NewLine();
					ImGui::Dummy(ImVec2(1, 10));
				}
			}
		}
	}
}

void NodeEditorWindow::renderSelectedObjectPanel()
{
	ImGui::SameLine();
	MkGuiScopedChild rightPanel("Right Panel", ImVec2(344, ImGui::GetContentRegionAvail().y));

	if (m_objectSelection.getObjectIdType() == GraphObjectIdType::NODE)
	{
		NodePtr node = getNodeGraph()->getNodeById(m_objectSelection.getObjectId(0));

		if (node)
		{
			node->editorRenderPropertySheet(m_editorState);
		}
	}
	else if (m_objectSelection.getObjectIdType() == GraphObjectIdType::ASSET)
	{
		const int assetIndex= m_objectSelection.getObjectId(0);
		const std::vector<AssetReferencePtr>& assetArray= getNodeGraph()->getAssetReferences();

		if (assetIndex >= 0 && assetIndex < (int)assetArray.size())
		{
			assetArray[assetIndex]->editorRenderPropertySheet(m_editorState);
		}
	}
	else if (m_objectSelection.getObjectIdType() == GraphObjectIdType::VARIABLE)
	{
		GraphPropertyPtr property = getNodeGraph()->getPropertyById(m_objectSelection.getObjectId(0));

		if (property)
		{
			property->editorRenderPropertySheet(m_editorState);
		}
	}
}

void NodeEditorWindow::deleteSelectedItem()
{
	if (m_objectSelection.getObjectIdType() == GraphObjectIdType::NODE)
	{
		for (int i = 0; i < m_objectSelection.getObjectCount(); i++)
		{
			const t_node_id nodeId= m_objectSelection.getObjectId(i);
			NodePtr node= getNodeGraph()->getNodeById(nodeId);

			if (node && node->editorCanDelete())
			{
				getNodeGraph()->deleteNodeById(nodeId);
			}
		}

		m_objectSelection.clear();
	}
	else if (m_objectSelection.getObjectIdType() == GraphObjectIdType::LINK)
	{
		for (int i = 0; i < m_objectSelection.getObjectCount(); i++)
		{
			const t_node_link_id linkId = m_objectSelection.getObjectId(i);

			getNodeGraph()->deleteLinkById(linkId);
		}

		m_objectSelection.clear();
	}
	else if (m_objectSelection.getObjectIdType() == GraphObjectIdType::VARIABLE)
	{
		for (int i = 0; i < m_objectSelection.getObjectCount(); i++)
		{
			const t_graph_property_id propertyId = m_objectSelection.getObjectId(i);

			getNodeGraph()->deletePropertyById(propertyId);
		}

		m_objectSelection.clear();
	}
	else if (m_objectSelection.getObjectIdType() == GraphObjectIdType::ASSET && 
			 m_objectSelection.getObjectCount() > 0)
	{
		std::vector<AssetReferencePtr>& assetList= getNodeGraph()->getAssetReferencesMutable();
		const int assetIndex = m_objectSelection.getObjectId(0);

		assetList.erase(assetList.begin() + assetIndex);
		m_objectSelection.clear();
	}
}

NodeGraphFactoryPtr NodeEditorWindow::getNodeGraphFactory() const 
{ 
	return std::make_shared<NodeGraphFactory>(); 
}

void NodeEditorWindow::newGraph()
{
	m_editorState.nodeGraph= getNodeGraphFactory()->initialCreateNodeGraph(this);
	onNodeGraphCreated();
}

bool NodeEditorWindow::loadGraph(const std::filesystem::path& path)
{
	m_editorState.nodeGraph= NodeGraphFactory::loadNodeGraph(this, path);
	if (m_editorState.nodeGraph)
	{
		m_editorState.nodeGraphPath= path;
		onNodeGraphCreated();
		return true;
	}
	else
	{
		MIKAN_LOG_ERROR("NodeEditorWindow::load") << "Failed to load node graph: " << path;
	}

	return false;
}

bool NodeEditorWindow::saveGraph(bool bShowFileDialog)
{
	// If no path was set or we explicitly want to show the file dialog,
	// bring up the save path dialog
	if (m_editorState.nodeGraphPath.empty() || bShowFileDialog)
	{
		std::string defautPath= (PathUtils::getResourceDirectory() / "graphs" / "new_graph.graph").string();
		const char* filterItems[1] = {"*.graph"};
		const char* filterDesc = "Graph Files (*.graph)";
		auto path = tinyfd_saveFileDialog("Save Compositor Graph", defautPath.c_str(), 1, filterItems, filterDesc);
		if (path)
		{
			m_editorState.nodeGraphPath= path;
		}
	}

	if (!m_editorState.nodeGraphPath.empty() && m_editorState.nodeGraph)
	{
		NodeGraphFactory::saveNodeGraph(m_editorState.nodeGraphPath, m_editorState.nodeGraph);
		return true;
	}

	return false;
}

void NodeEditorWindow::undo()
{
	//TODO
}

void NodeEditorWindow::onNodeGraphCreated()
{
	MkGuiScopedContext scopedContext(*m_guiContext.get());
	NodeGraphPtr graph= getNodeGraph();

	graph->OnNodeCreated += MakeDelegate(this, &NodeEditorWindow::onNodeCreated);
	graph->OnNodeDeleted += MakeDelegate(this, &NodeEditorWindow::onNodeDeleted);
	graph->OnLinkDeleted += MakeDelegate(this, &NodeEditorWindow::onLinkDeleted);
	graph->OnPropertyCreated += MakeDelegate(this, &NodeEditorWindow::onGraphPropertyCreated);
	graph->OnPropertyModifed += MakeDelegate(this, &NodeEditorWindow::onGraphPropertyModified);
	graph->OnPropertyDeleted += MakeDelegate(this, &NodeEditorWindow::onGraphPropertyDeleted);

	// Register the node positions with ImNode
	for (auto iter = graph->getNodesMap().begin(); iter != graph->getNodesMap().end(); iter++)
	{
		const t_node_id nodeId = iter->first;
		NodePtr node= iter->second;

		const glm::vec2& nodePos= node->getNodePos();
		ImNodes::SetNodeGridSpacePos(nodeId, {nodePos.x, nodePos.y});
	}
}

void NodeEditorWindow::onNodeGraphDeleted()
{
	NodeGraphPtr graph= getNodeGraph();

	if (graph)
	{
		graph->OnNodeCreated -= MakeDelegate(this, &NodeEditorWindow::onNodeCreated);
		graph->OnNodeDeleted -= MakeDelegate(this, &NodeEditorWindow::onNodeDeleted);
		graph->OnLinkDeleted -= MakeDelegate(this, &NodeEditorWindow::onLinkDeleted);
		graph->OnPropertyCreated -= MakeDelegate(this, &NodeEditorWindow::onGraphPropertyCreated);
		graph->OnPropertyModifed -= MakeDelegate(this, &NodeEditorWindow::onGraphPropertyModified);
		graph->OnPropertyDeleted -= MakeDelegate(this, &NodeEditorWindow::onGraphPropertyDeleted);
	}
}

void NodeEditorWindow::onNodeCreated(t_node_id id)
{
	// Set the initial position of the node using the current editor mouse position
	const ImVec2& hangPosGridSpace = m_editorState.hangPosGridSpace;
	ImNodes::SetNodeGridSpacePos(id, hangPosGridSpace);
	NodePtr node= getNodeGraph()->getNodeById(id);
	if (node)
	{
		node->setNodePos(glm::vec2(hangPosGridSpace.x, hangPosGridSpace.y));
	}

	// Make the newly created node selected
	m_objectSelection = GraphObjectSelection(GraphObjectIdType::NODE, 1);
	m_objectSelection.setObjectId(0, id);

	ImNodes::ClearLinkSelection();
	ImNodes::ClearNodeSelection();
	ImNodes::SelectNode(id);

}

void NodeEditorWindow::onNodeDeleted(t_node_id id)
{
	if (m_objectSelection.getObjectIdType() == GraphObjectIdType::NODE &&
		m_objectSelection.removeObjectId(id))
	{
		ImNodes::ClearNodeSelection();
	}
}

void NodeEditorWindow::onLinkDeleted(t_node_link_id id)
{
	if (m_objectSelection.getObjectIdType() == GraphObjectIdType::LINK &&
		m_objectSelection.removeObjectId(id))
	{
		ImNodes::ClearLinkSelection();
	}
}

void NodeEditorWindow::shutdown()
{
	onNodeGraphDeleted();
	m_editorState.nodeGraph= nullptr;
	m_editorState.nodeGraphPath.clear();

	m_mkStateStack = nullptr;

	if (m_shaderCache != nullptr)
	{
		m_shaderCache->shutdown();
		m_shaderCache = nullptr;
	}

	if (m_textureCache != nullptr)
	{
		m_textureCache->shutdown();
		m_textureCache = nullptr;
	}

	if (m_styleManager != nullptr)
	{
		m_styleManager->shutdown();
		m_styleManager = nullptr;
	}

	if (m_guiContext != nullptr)
	{
		m_guiContext->shutdown();
		m_guiContext = nullptr;
	}

	if (m_sdlWindow != nullptr)
	{
		m_sdlWindow->shutdown();
		m_sdlWindow = nullptr;
	}
}
 
float NodeEditorWindow::getWidth() const
{
	return (float)m_sdlWindow->getWidth();
}

float NodeEditorWindow::getHeight() const
{
	return (float)m_sdlWindow->getHeight();
}

float NodeEditorWindow::getAspectRatio() const
{
	return (float)m_sdlWindow->getAspectRatio();
}

// -- IMkWindowEventListener
bool NodeEditorWindow::onWindowEvent(const SDL_Event* event)
{
	return m_guiContext->onWindowEvent(event);
}

// -- IEditorWindow
MainWindow* NodeEditorWindow::getMainWindow() const
{
	return getOwnerApp()->getMainWindow();
}

ProjectManagerPtr NodeEditorWindow::getProjectManager() const
{
	return getMainWindow()->getProjectManager();
}

MikanServer* NodeEditorWindow::getMikanServer() const
{
	return getMainWindow()->getMikanServer();
}

MikanFontManager* NodeEditorWindow::getFontManager() const
{
	return getMainWindow()->getFontManager();
}

InputManager* NodeEditorWindow::getInputManager() const
{
	return getMainWindow()->getInputManager();
}

OpenCVManager* NodeEditorWindow::getOpenCVManager() const
{
	return getMainWindow()->getOpenCVManager();
}

ClientSourceManager* NodeEditorWindow::getClientSourceManager() const
{
	return getMainWindow()->getClientSourceManager();
}

LocalizationManager* NodeEditorWindow::getLocalizationManager() const
{
	return getMainWindow()->getLocalizationManager();
}

EventBus* NodeEditorWindow::getEventBus() const
{
	return getMainWindow()->getEventBus();
}

MkGuiStyleManager* NodeEditorWindow::getMkGuiStyleManager() const
{
	return m_styleManager.get();
}

App* NodeEditorWindow::getOwnerApp() const
{
	return m_ownerApp;
}

AppStage* NodeEditorWindow::getCurrentAppStage() const
{
	return getMainWindow()->getCurrentAppStage();
}

AppStage* NodeEditorWindow::getParentAppStage() const
{
	return getMainWindow()->getParentAppStage();
}

AppStage* NodeEditorWindow::pushAppStage(const std::string& appStageName)
{
	return getMainWindow()->pushAppStage(appStageName);
}

void NodeEditorWindow::popAppState()
{
	return getMainWindow()->popAppState();
}

