//-- includes -----
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <cstring>

#include "ARKitWireProtocol.h"
#include "unit_test.h"

//-- private functions -----
static bool arkit_wire_protocol_test_pose_packet_roundtrip()
{
	UNIT_TEST_BEGIN("pose packet roundtrip")

	ARKitPosePacket packet;
	packet.frameSeq= 42;
	packet.captureTimestampUs= 1234567890123ULL;
	for (int i= 0; i < 16; ++i)
	{
		packet.transform[i]= (i == 0 || i == 5 || i == 10 || i == 15) ? 1.0f : 0.0f; // identity
	}
	packet.fx= 1428.5f;
	packet.fy= 1428.5f;
	packet.cx= 960.25f;
	packet.cy= 540.75f;
	packet.imageWidth= 1920.0f;
	packet.imageHeight= 1080.0f;

	uint8_t buffer[ARKitPosePacket::kWireSize]= {};
	size_t written= writeARKitPosePacket(buffer, sizeof(buffer), packet);
	success= (written == ARKitPosePacket::kWireSize);
	assert(success);

	ARKitPosePacket roundTripped;
	success= success && readARKitPosePacket(buffer, sizeof(buffer), roundTripped);
	assert(success);

	success= success && roundTripped.frameSeq == packet.frameSeq;
	success= success && roundTripped.captureTimestampUs == packet.captureTimestampUs;
	for (int i= 0; success && i < 16; ++i)
	{
		success= (roundTripped.transform[i] == packet.transform[i]);
	}
	assert(success);
	success= success && roundTripped.fx == packet.fx;
	success= success && roundTripped.fy == packet.fy;
	success= success && roundTripped.cx == packet.cx;
	success= success && roundTripped.cy == packet.cy;
	success= success && roundTripped.imageWidth == packet.imageWidth;
	success= success && roundTripped.imageHeight == packet.imageHeight;
	assert(success);

	UNIT_TEST_COMPLETE()
}

static bool arkit_wire_protocol_test_rtp_extension_payload_roundtrip()
{
	UNIT_TEST_BEGIN("RTP extension payload roundtrip")

	ARKitRTPExtensionPayload payload;
	payload.frameSeq= 0x00112233;
	payload.captureTimestampUs= 0x0011223344556677ULL;

	uint8_t buffer[ARKitRTPExtensionPayload::kWireSize]= {};
	size_t written= writeARKitRTPExtensionPayload(buffer, sizeof(buffer), payload);
	success= (written == ARKitRTPExtensionPayload::kWireSize);
	assert(success);

	ARKitRTPExtensionPayload roundTripped;
	success= success && readARKitRTPExtensionPayload(buffer, sizeof(buffer), roundTripped);
	assert(success);

	success= success && roundTripped.frameSeq == payload.frameSeq;
	success= success && roundTripped.captureTimestampUs == payload.captureTimestampUs;
	assert(success);

	UNIT_TEST_COMPLETE()
}

static bool arkit_wire_protocol_test_pose_in_rtp_payload_roundtrip()
{
	UNIT_TEST_BEGIN("pose-in-RTP payload (100-byte, header-less) roundtrip")

	ARKitPoseInRTPPayload payload;
	payload.frameSeq= 42;
	payload.captureTimestampUs= 1234567890123ULL;
	for (int i= 0; i < 16; ++i)
	{
		payload.transform[i]= (i == 0 || i == 5 || i == 10 || i == 15) ? 1.0f : 0.0f; // identity
	}
	payload.fx= 1428.5f;
	payload.fy= 1428.5f;
	payload.cx= 960.25f;
	payload.cy= 540.75f;
	payload.imageWidth= 1920.0f;
	payload.imageHeight= 1080.0f;

	uint8_t buffer[ARKitPoseInRTPPayload::kWireSize]= {};
	size_t written= writeARKitPoseInRTPPayload(buffer, sizeof(buffer), payload);
	success= (written == ARKitPoseInRTPPayload::kWireSize);
	assert(success);

	ARKitPoseInRTPPayload roundTripped;
	success= success && readARKitPoseInRTPPayload(buffer, sizeof(buffer), roundTripped);
	assert(success);

	success= success && roundTripped.frameSeq == payload.frameSeq;
	success= success && roundTripped.captureTimestampUs == payload.captureTimestampUs;
	for (int i= 0; success && i < 16; ++i)
	{
		success= (roundTripped.transform[i] == payload.transform[i]);
	}
	assert(success);
	success= success && roundTripped.fx == payload.fx;
	success= success && roundTripped.fy == payload.fy;
	success= success && roundTripped.cx == payload.cx;
	success= success && roundTripped.cy == payload.cy;
	success= success && roundTripped.imageWidth == payload.imageWidth;
	success= success && roundTripped.imageHeight == payload.imageHeight;
	assert(success);

	// Undersized buffers must be rejected, not partially decoded.
	success= (readARKitPoseInRTPPayload(buffer, ARKitPoseInRTPPayload::kWireSize - 1, roundTripped) == false);
	assert(success);
	success= (writeARKitPoseInRTPPayload(buffer, ARKitPoseInRTPPayload::kWireSize - 1, payload) == 0);
	assert(success);

	UNIT_TEST_COMPLETE()
}

// Cross-repo byte-exactness check (Phase 4 of the pose-in-RTP migration): asserts
// the exact same 100-byte literal that `H264RTPPacketizerTests.swift`'s
// `testPoseInRTPPayloadCrossCheckFixture` builds via `H264RTPPacketizer`'s
// pose-extension encoder decodes back to the same float/frameSeq/timestamp
// values here. Catches a row/col transpose or endianness inversion the same way
// the now-deleted `arkit_rvl_swift_crosscheck_unit_tests.cpp` did for RVL - the
// cheapest way to find that bug is a byte-identical fixture shared across repos,
// not two independently-written encoders that could independently agree on the
// wrong thing. The literal below was generated by this repo's own
// writeARKitPoseInRTPPayload() (not hand-computed - IEEE-754 float byte patterns
// are exactly the kind of thing that's easy to get subtly wrong by hand) and then
// copied verbatim into the Swift test's expected-bytes assertion; if either
// side's transpose/endianness logic disagrees, one of the two tests fails.
static bool arkit_wire_protocol_test_swift_pose_in_rtp_crosscheck()
{
	UNIT_TEST_BEGIN("pose-in-RTP payload byte-exact crosscheck against the Swift sender's expected fixture")

	// clang-format off
	static const uint8_t kExpectedBytes[ARKitPoseInRTPPayload::kWireSize]= {
		0x00, 0x00, 0x03, 0x09, 0x00, 0x00, 0x00, 0x00,
		0x07, 0x5B, 0xCD, 0x15, 0x3F, 0x80, 0x00, 0x00,
		0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
		0x41, 0x20, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
		0x3F, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
		0x41, 0xA0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
		0x00, 0x00, 0x00, 0x00, 0x3F, 0x80, 0x00, 0x00,
		0x41, 0xF0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
		0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
		0x3F, 0x80, 0x00, 0x00, 0x44, 0x7A, 0x00, 0x00,
		0x44, 0x7A, 0x00, 0x00, 0x44, 0x20, 0x00, 0x00,
		0x43, 0xB4, 0x00, 0x00, 0x44, 0xA0, 0x00, 0x00,
		0x44, 0x34, 0x00, 0x00,
	};
	// clang-format on

	ARKitPoseInRTPPayload decoded;
	success= readARKitPoseInRTPPayload(kExpectedBytes, sizeof(kExpectedBytes), decoded);
	assert(success);

	// frameSeq=777, timestampUs=123456789 - the same fixture values the Swift
	// test's `ARCaptureController`-shaped inputs use.
	success= success && (decoded.frameSeq == 777);
	success= success && (decoded.captureTimestampUs == 123456789ULL);
	assert(success);

	// Row-major camera-to-world translation of (10, 20, 30), identity rotation -
	// chosen specifically so the row/col transpose is trivially eyeballable
	// (translation values land in the last column of each row) rather than
	// needing a non-trivial matrix to catch a transpose bug.
	const float expectedTransform[16]= {1, 0, 0, 10, 0, 1, 0, 20, 0, 0, 1, 30, 0, 0, 0, 1};
	for (int i= 0; success && i < 16; ++i)
	{
		success= (decoded.transform[i] == expectedTransform[i]);
	}
	assert(success);

	success= success && decoded.fx == 1000.0f;
	success= success && decoded.fy == 1000.0f;
	success= success && decoded.cx == 640.0f;
	success= success && decoded.cy == 360.0f;
	success= success && decoded.imageWidth == 1280.0f;
	success= success && decoded.imageHeight == 720.0f;
	assert(success);

	UNIT_TEST_COMPLETE()
}

static bool arkit_wire_protocol_test_be_primitive_helpers()
{
	UNIT_TEST_BEGIN("big-endian primitive helpers")

	uint8_t buffer[8]= {};

	writeU16BE(buffer, 0xABCD);
	success= (buffer[0] == 0xAB && buffer[1] == 0xCD);
	success= success && (readU16BE(buffer) == 0xABCD);
	assert(success);

	writeU32BE(buffer, 0x11223344);
	success= success && (buffer[0] == 0x11 && buffer[1] == 0x22 && buffer[2] == 0x33 && buffer[3] == 0x44);
	success= success && (readU32BE(buffer) == 0x11223344);
	assert(success);

	writeU64BE(buffer, 0x0102030405060708ULL);
	success= success && (buffer[0] == 0x01 && buffer[7] == 0x08);
	success= success && (readU64BE(buffer) == 0x0102030405060708ULL);
	assert(success);

	writeF32BE(buffer, -12345.678f);
	success= success && (readF32BE(buffer) == -12345.678f);
	assert(success);

	UNIT_TEST_COMPLETE()
}

//-- public interface -----
bool run_arkit_wire_protocol_unit_tests()
{
	UNIT_TEST_MODULE_BEGIN("arkit_wire_protocol")
	UNIT_TEST_MODULE_CALL_TEST(arkit_wire_protocol_test_be_primitive_helpers);
	UNIT_TEST_MODULE_CALL_TEST(arkit_wire_protocol_test_pose_packet_roundtrip);
	UNIT_TEST_MODULE_CALL_TEST(arkit_wire_protocol_test_rtp_extension_payload_roundtrip);
	UNIT_TEST_MODULE_CALL_TEST(arkit_wire_protocol_test_pose_in_rtp_payload_roundtrip);
	UNIT_TEST_MODULE_CALL_TEST(arkit_wire_protocol_test_swift_pose_in_rtp_crosscheck);
	UNIT_TEST_MODULE_END()
}
