#include "GlProgramConstants.h"

const std::string g_UniformSemanticName[(int)eUniformSemantic::COUNT] = {
	"transformMatrix",
	"modelMatrix",
	"inverseModelMatrix",
	"viewMatrix",
	"projectionMatrix",
	"modelViewProjectionMatrix",
	"diffuseColorRGBA",
	"cameraPosition",
	"ambientColorRGB",
	"diffuseColorRGB",
	"specularColorRGB",
	"lightColorRGB",
	"lightDirection",
	"screenPosition",
	"specularHighlights",
	"opticalDensity",
	"dissolve",
	"zNear",
	"zFar",
	"floatConstant0",
	"floatConstant1",
	"floatConstant2",
	"floatConstant3",
	"ambientTexture",
	"diffuseTexture",
	"specularTexture",
	"specularHightlightTexture",
	"alphaTexture",
	"bumpTexture",
	"rgbTexture",
	"rgbaTexture",
	"distortionTexture",
	"depthTexture"
};
const std::string* k_UniformSemanticName = g_UniformSemanticName;