#pragma once

#include <RmlUi/Config/Config.h>
#include <RmlUi/Core/Decorator.h>

#include "OpenCVFwd.h"

namespace Rml {
	struct Vertex;
}

class DecoratorArucoMarker : public Rml::Decorator
{
public:
	DecoratorArucoMarker();
	virtual ~DecoratorArucoMarker();

	/// Initialize the decorator with ArUco dictionary type, marker ID and physical size
	bool Initialise(int dictionaryTypeInt, int markerId, int markerSize);

	/// Called on a decorator to generate any required per-element data for a newly decorated element.
	/// @param element[in] The newly decorated element.
	/// @return A handle to a decorator-defined data handle, or nullptr if none is needed for the element.
	Rml::DecoratorDataHandle GenerateElementData(Rml::Element* element) const override;

	/// Called to release element data generated by this decorator.
	/// @param element_data[in] The element data handle to release.
	void ReleaseElementData(Rml::DecoratorDataHandle element_data) const override;

	/// Called to render the decorator on an element.
	/// @param element[in] The element to render the decorator on.
	/// @param element_data[in] The handle to the data generated by the decorator for the element.
	void RenderElement(Rml::Element* element, Rml::DecoratorDataHandle element_data) const override;

private:
	void GenerateGeometry(
		Rml::Vector< Rml::Vertex >& vertices,
		Rml::Vector< int >& indices, 
		Rml::Element* element) const;

	/// Generate ArUco marker texture for the given marker ID and size
	bool GenerateMarkerTexture(int markerId, int markerSize);

	/// Generate ArUco marker and create texture data for RmlUI callback
	bool CreateTextureFromMat(int markerId, int markerSize, Rml::UniquePtr<const Rml::byte[]>& data, Rml::Vector2i& dimensions);

	/// ArUco marker properties
	int m_markerId;
	int m_markerSize;

	/// ArUco dictionary (DICT_6X6_250)
	ArucoDictionaryPtr m_dictionary;
};